### ISSUE TITLE
Add feature progress to testPass/testFail protractor events.

### ISSUE THREAD

**Issue by darrinholst** [protractor-cucumber-framework/protractor-cucumber-framework#105]
As discussed in #103 we emit testPass/testFail events at the step level in order to provide more context to IDEs such as webstorm. This allows them to visualize and navigate the steps which is useful.

This causes problems for other tools that want to know when the encompassing feature is done.

I think we can satisfy both camps by adding a percentage complete or a "step x of y" property to the [event details](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/blob/master/lib/resultsCapturer.js#L236).

**Comment by phenomnomnominal** [comment]
I'll take a crack at a PR for this one
