### ISSUE TITLE
Cucumber Cannot find Step Definitons Please help

### ISSUE THREAD

**Issue by prasannarhegde2015** [protractor-cucumber-framework/protractor-cucumber-framework#108]
Protractor Version : 5.1.2
Cucumber Version latest (installed using npm install -g cucumber)
let me know how to check version of cucumber cucumber --version throws error

Environment: Windows 10
Protractor is not able to execute cucumber steps it cant find steps definitions
Few days back was working fine on same system
not sure what changed after which it stopped working
Searched google a lot did not get it working after trying workarounds suggested

Let me know how to trouble shoot issue

**Comment by darrinholst** [comment]
I'd probably start by not using global installations of protractor and cucumber and install them locally to the project. This way it's easier to determine what changed between working and non-working states.

That being said, if you upgraded from a version of cucumber before version 2 then that's not a drop-in replacement. You'll have to make some changes to how you define your step definitions. See [cucumber 2 steps](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/blob/master/test/cucumber/stepDefinitions/cucumber2Steps.js) for an example. Or [this project](https://github.com/dholst/protractor-cucumber-framework-example) for a complete working example.

`cucumber-js` is the binary you need to show the version

``` bash
✓ cucumber-js --version
3.0.5
```
