### ISSUE TITLE
framework fails when fullstops in project folder name.

### ISSUE THREAD

**Issue by GWillits** [protractor-cucumber-framework/protractor-cucumber-framework#109]
Hi. We have an issue running the PCF when the enclosing folder has a name with full stops.
We couldn't understand why a sandbox application ran fine but a branch failed until I tried to rename the sandbox to be the same as the trunk and verified that this was the probable cause. 
This is the error message:

Unhandled rejection Error: Cannot find module 'C:\Projects\test-projs\ang-cucumber\iViewPlus.External.Web.v2\iViewPlus.External.Web.v2\node_modules\prot
ractor-cucumber-framework\lib\resultsCapturer.js'

If you look you can see that the folder name (iViewPlus.External.Web.v2) is repeated twice whereas there is only one folder with that name. Could something be splitting on full stops and getting confused when generating the path to resultsCapture.js?

Same code running with the fullstops removed:
1 scenario (1 passed)
4 steps (4 passed)
0m01.982s
Cucumber HTML report D:\development\git-svn\iViewPlusExternalWebv2\reports\html/cucumber
_reporter.html generated successfully.

I can keep my code branched while I develop my test suite. However renaming the folder will cause a big pain to the team because of git / SVN. I'm hoping this will be an easy fix now that I've identified the issue.
Look forward to seeing an update and keep up the good work.

**Comment by darrinholst** [comment]
Let me know if `4.0.9` doesn't fix it for you.

**Comment by GWillits** [comment]
A new issue has been identified in #110
