### ISSUE TITLE
resultsCapturer.js - Unhandled rejection Error: ENOENT: no such file or directory, open 

### ISSUE THREAD

**Issue by Galileo1** [protractor-cucumber-framework/protractor-cucumber-framework#112]
Has anyone able to solve the following issue? Even though file is there but node still throws the error. 
I have tried both node v 4.x and node v 6.x but it doesn't resolves the problem. 

  dependencies": {
    "bluebird": "3.5.1",
    "chai": "4.1.2",
    "chai-as-promised": "7.1.1",
    "cucumber": "3.0.5",
    "protractor": "5.2.0",
    "protractor-cucumber-framework": "4.0.9"
  }

Unhandled rejection Error: ENOENT: no such file or directory, open 'C:\Users\xxxx\javascript\PeopleSoftHR\Test\node_modules\protractor-cucumber-framework\lib\resultsCapturer.js:C:\Users\xxxxx~1\AppData\Local\Temp\tmp-15080AFeyk4DDpqwb.tmp'
    at Error (native)

**Comment by Galileo1** [comment]
downgrading to v4.0.3 solves this issue for now.

**Comment by darrinholst** [comment]
4.0.9 was supposed to be a bug fix, but it ended up breaking things for windows users. The next cucumber release should fix it again. See #110
