### ISSUE TITLE
Selenium promise manager not working

### ISSUE THREAD

**Issue by hung-doan** [protractor-cucumber-framework/protractor-cucumber-framework#115]
Protractor: Version 5.2.0
Cucumber: Version 3.1.0
protractor-cucumber-framework: Version 4.1.1

**Protractor only:** 
```
it('should add one and two', function() {
        browser.driver.get('https://abc.com/');
        browser.driver.findElement(by.id('Email')).sendKeys("email");
        browser.driver.findElement(by.id('Password')).sendKeys("pass");
        browser.driver.findElement(by.id('loginBtn')).click();
});
```
it work as expected. 

**Protractor + Cucumber + protractor-cucumber-framework**, I need to manage the async by myself. It seem that promise manager not work.  

I try to set SELENIUM_PROMISE_MANAGER = true, or process.env.SELENIUM_PROMISE_MANAGER = 1, but still not working.

This code not working (passed the test without do nothing to the browser): 
```
Given(/^I have logged in$/,{timeout: 60 * 1000}, function() {
        browser.driver.get('https://abc.com/');
        browser.driver.findElement(by.id('Email')).sendKeys("email");
        browser.driver.findElement(by.id('Password')).sendKeys("pass");
        browser.driver.findElement(by.id('loginBtn')).click();
    });    

```

This code is working: 
```
Given(/^I have logged in$/,{timeout: 60 * 1000}, function() {
        return browser.driver.get('https://abc.com/')
            .then(_ => browser.driver.findElement(by.id('Email')).sendKeys("admin@groove.com"))
            .then(_ => browser.driver.findElement(by.id('Password')).sendKeys("Password@1"))
            .then(_ => browser.driver.findElement(by.id('loginBtn')).click());
    });    

```

**Comment by hung-doan** [comment]
It seem relate to this previous issue: https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/issues/60

**Comment by darrinholst** [comment]
you need to return that last promise. All of those statements just queue the actions to happen and the step is over before anything is ever done.

``` javascript
Given(/^I have logged in$/,{timeout: 60 * 1000}, function() {
  browser.driver.get('https://abc.com/');
  browser.driver.findElement(by.id('Email')).sendKeys("email");
  browser.driver.findElement(by.id('Password')).sendKeys("pass");
  return browser.driver.findElement(by.id('loginBtn')).click();
});   
```

**Comment by hung-doan** [comment]
thanks @darrinholst. So, If I use Protractor with Jasmine syntax. Protractor, somehow It manages the promise chain for me(I mean I do not need return the promise to Protractor). With Cucumber, I have to handle it  by myself by returning a promise or calling complete callback.

**Comment by darrinholst** [comment]
There was PR #61 to make that happen for cucumber 1, but it didn't work for cucumber 2+. You'll have to manually handle the returned promises for now.
