### ISSUE TITLE
How do you pass more than one tags?

### ISSUE THREAD

**Issue by chfw** [protractor-cucumber-framework/protractor-cucumber-framework#116]
I have tried v4.1.1 with cucumber.js 2.3.2 and 3.1.0. Whenever I specify two tags, protractor fails to run any scenarios.

```
        cucumberOpts: {
            tags: ['@search', '@contact']  // <- does not work and protractor does nothing.
        },
```

And it runs only when one and only one tag is mentioned in protractor.conf.js

```
        cucumberOpts: {
            tags: '@search'  // <- works
        },
```

Did I miss anything?

**Comment by darrinholst** [comment]
“Should” work. Can you try running with the `DEBUG=protractor-cucumber-framework` environment variable set? That should print out the command that’s being run.

**Comment by chfw** [comment]
` protractor-cucumber-framework cucumber command: "node cucumberjs --compiler .... --tags @contact and @search ....`

However, the documentation says: 

> Tags which are passed in separate --tags are ANDed
> 
> Example: Running scenarios which match @important AND @billing
> 
> cucumber --tags @billing --tags @important
> You can combine these two methods to create powerful selection criteria:
> 
> Example: Running scenarios which match: (@billing OR @WIP) AND @important
> 
> cucumber --tags @billing,@wip --tags @important
> 
> https://github.com/cucumber/cucumber/wiki/Tags#logically-anding-and-oring-tags

so, is it a bug?

**Comment by darrinholst** [comment]
It used to use tag expressions https://docs.cucumber.io/tag-expressions/

Looks like we need some tests for multiple tags

**Comment by darrinholst** [comment]
It's working as expected - https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/blob/master/test/tags.spec.js#L3

I think you want `@search` __or__ `@contact`, but multiple tags will __and__ by default so the scenarios would need to have both of those tags.

You'll need to use the tag expressions to get `or`ing, i.e.

    --tags '@search or @contact`

Let me know if this isn't the case.

**Comment by csvan** [comment]
@chfw I can confirm that this works. For example:

```
tags:  [
            '~@in-progress',
            '@firstFeature or @otherFeature'
      ]
```

Will run all features which do **not** have @in-progess **and** have the tag @firstFeature **or** the tag @otherFeature

**Comment by chfw** [comment]
yes, I also confirm that it works 👍 . keep up the good work.

**Comment by kiranshan** [comment]
> @chfw I can confirm that this works. For example:
> 
> ```
> tags:  [
>     '~@in-progress',
>     '@firstFeature or @otherFeature'
> ]
> ```
> 
> Will run all features which do **not** have @in-progress tags **and** have the tag @firstFeature **or** the tag @otherFeature.

I gave tired this is not working
Please check if your are able to get the work done and confirm again
