### ISSUE TITLE
Undefined step references

### ISSUE THREAD

**Issue by piotro83** [protractor-cucumber-framework/protractor-cucumber-framework#117]
HI @darrinholst @AlexandrosD  , maybe you help me?

Why i have Undefined step references in first step?
https://wpde.sk/pp/1rnzk.png

` "devDependencies": {`
    `"cucumber": "~3.2.0",`
    `"protractor": "~5.2.1",`
    `"protractor-cucumber-framework": "~4.1.1",`
    `"selenium-webdriver": "~3.6.0",`
    `"cucumber-expressions": "5.0.7"`
	},`
> exports.config = {
    allScriptsTimeout: TIMEOUT,
    getPageTimeout: TIMEOUT,
    baseUrl: 'http://localhost/test',
    rootElement: 'body',
    framework: 'custom',
    frameworkPath: require.resolve('protractor-cucumber-framework'),
    specs: [
        '../test-acceptance/features/test.feature',
    ],
    cucumberOpts: {
        compiler: "es6:babel-core/register",
        require: '../test-acceptance/features/**/*/*.js',
        keepAlive: false,
    },

**Second problem**
when i run test i have 2 Undefined steps:
> Warnings:

1) Scenario: test # test-acceptance\features\test.feature:3
   ? When I have 3 cucumbers in my belly
       Undefined. Implement with the following snippet:

         When('I have {int} cucumbers in my belly', function (int, callback) {
           // Write code here that turns the phrase above into concrete actions
           callback(null, 'pending');
         });

   ? When I give you 3 toys
       Undefined. Implement with the following snippet:

         When('I give you {int} toys', function (int, callback) {
           // Write code here that turns the phrase above into concrete actions
           callback(null, 'pending');
         });

**Comment by darrinholst** [comment]
Your image shows you defining steps with `this.`. That's not how you define them from cucumber 2 and up. See https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/blob/master/test/cucumber/stepDefinitions/cucumber2Steps.js for an example
