### ISSUE TITLE
function timed out issue

### ISSUE THREAD

**Issue by vinodkpasi** [protractor-cucumber-framework/protractor-cucumber-framework#119]
Hello, cucumber-js is new for me. I’m trying to do the nodejs example, I get following error:
Scenario: Tabs Functionality - Test_Modules\LCC\Features\tabs.feature:2
   Step: Given Using Tab functionality - Test_Modules\LCC\Features\tabs.feature:3
   Step Definition: Test_Modules\LCC\step_definitions\tabs.js:2
   Message:
     **function timed out after 100000 milliseconds**

**Comment by AlexandrosD** [comment]
Hi, you are probably confusing cucumber-js with
protractor-cucumber-framework ..

2018-01-22 9:04 GMT+01:00 vinodkpasi <notifications@github.com>:
