### ISSUE TITLE
WebDriverError: no such session when control flow is disabled and restartBrowserBetweenTests: true

### ISSUE THREAD

**Issue by pumbox** [protractor-cucumber-framework/protractor-cucumber-framework#121]
'WebDriverError: no such session' error is thrown on attempt to run test. Test execution begins before session is created. 

- The issue is reproducing with following configuration:
-- Control flow should be disabled. 
-- restartBrowserBetweenTests: true

- Is not reproducing when restartBrowserBetweenTests: false and control flow is disabled
- Is not reproducing when restartBrowserBetweenTests: true and control flow is enabled
- Is not reproducing with "jasmine":"2.8.0"

"cucumber": "4.0.0",
"protractor": "5.3.0",
"protractor-cucumber-framework": "4.2.0"

```
1) Scenario: test scenario # features/aFeatureFile.feature:11
   ✖ Given I execute test # features/homePage_steps.js:1
       WebDriverError: no such session
         (Driver info: chromedriver=2.35.528157 (4429ca2590d6988c0745c24c8858745aaaec01ef),platform=Mac OS X 10.13.2 x86_64)> > > 
```

config file example
```
const config = {
    SELENIUM_PROMISE_MANAGER: false,
    baseUrl: "http://www.angularjs.org",
    seleniumAddress: 'http://localhost:4444/wd/hub',
    capabilities: {
        browserName: 'chrome',
        shardTestFiles: false,
        maxInstances: 1
    },
    specs: [
        './features/*.feature'
    ],
    ignoreUncaughtExceptions: true,
    disableChecks: true,
    framework: 'custom',
    frameworkPath: './node_modules/protractor-cucumber-framework',
    restartBrowserBetweenTests: true,
    cucumberOpts: {
        require: './features/homePage_steps.js',
        strict: true,
        format: 'json:results.json',
        defaultTimeoutInterval: 160000,
        tags: "@Regression"
    },
    onPrepare: onPrepare,
    onComplete: onComplete
};

function onPrepare() {
    const {Given, Then, When} = require('cucumber');
    global.Given = Given;
    global.When = When;
    global.Then = Then;
}

function onComplete() {
    console.log("suite tests complete --> ");
}

exports.config = Object.assign({}, config);
```

log from selenium standalone

```
10:55:50.199 INFO - Binding default provider to: org.openqa.selenium.chrome.ChromeDriverService
10:55:50.199 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.BeginSession@7c612334
10:55:50.199 INFO - /session: Executing POST on /session (handler: BeginSession)
10:55:50.200 INFO - Capabilities are: Capabilities {count=1, browserName=chrome, maxInstances=1, shardTestFiles=false, }
10:55:50.200 INFO - Capabilities {count=1, browserName=chrome, maxInstances=1, shardTestFiles=false, } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
10:55:50.200 INFO - Capabilities {count=1, browserName=chrome, maxInstances=1, shardTestFiles=false, } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 2.35.528157 (4429ca2590d6988c0745c24c8858745aaaec01ef) on port 37608
Only local connections are allowed.
10:55:51.045 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@32723eb3
10:55:51.047 INFO - Handler thread for session 374edcf42644e4382becdb360ce402fd (chrome): Executing POST on /session/374edcf42644e4382becdb360ce402fd/timeouts (handler: ServicedSession)
10:55:51.049 INFO - To upstream: {"script":11000}
10:55:51.051 INFO - To downstream: {"sessionId":"374edcf42644e4382becdb360ce402fd","status":13,"value":{"message":"unknown error: 'ms' must be a double\n  (Session info: chrome=63.0.3239.132)\n  (Driver info: chromedriver=2.35.528157 (4429ca2590d6988c0745c24c8858745aaaec01ef),platform=Mac OS X 10.13.2 x86_64)"}}
10:55:51.055 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@32723eb3
10:55:51.055 INFO - Handler thread for session 374edcf42644e4382becdb360ce402fd (chrome): Executing POST on /session/374edcf42644e4382becdb360ce402fd/timeouts (handler: ServicedSession)
10:55:51.056 INFO - To upstream: {"type":"script","ms":11000}
10:55:51.056 INFO - To downstream: {"sessionId":"374edcf42644e4382becdb360ce402fd","status":0,"value":null}
10:55:51.635 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@32723eb3
10:55:51.635 INFO - Handler thread for session 374edcf42644e4382becdb360ce402fd (chrome): Executing POST on /session/374edcf42644e4382becdb360ce402fd/url (handler: ServicedSession)
10:55:51.635 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@32723eb3
10:55:51.636 INFO - To upstream: {"url":"data:text/html,<html></html>"}
10:55:51.637 INFO - Handler thread for session 374edcf42644e4382becdb360ce402fd (chrome): Executing DELETE on /session/374edcf42644e4382becdb360ce402fd (handler: ServicedSession)
10:55:51.679 INFO - To downstream: {"sessionId":"374edcf42644e4382becdb360ce402fd","status":0,"value":null}
10:55:51.685 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@32723eb3
10:55:51.686 INFO - Handler thread for session 374edcf42644e4382becdb360ce402fd (chrome): Executing POST on /session/374edcf42644e4382becdb360ce402fd/execute (handler: ServicedSession)
10:55:51.686 INFO - To upstream: {"script":"window.name = \"NG_DEFER_BOOTSTRAP!\" + window.name;window.location.replace(\"http://www.angularjs.org/\");","args":[]}
10:55:51.729 INFO - To downstream: {"sessionId":"374edcf42644e4382becdb360ce402fd","status":0,"value":null}
10:55:51.730 INFO - Removing session org.openqa.selenium.remote.server.ServicedSession@32723eb3
10:55:51.741 INFO - Binding default provider to: org.openqa.selenium.chrome.ChromeDriverService
10:55:51.741 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.BeginSession@685da0da
10:55:51.741 INFO - /session: Executing POST on /session (handler: BeginSession)
10:55:51.742 INFO - Capabilities are: Capabilities {count=1, browserName=chrome, maxInstances=1, shardTestFiles=false, }
10:55:51.742 INFO - Capabilities {count=1, browserName=chrome, maxInstances=1, shardTestFiles=false, } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
10:55:51.742 INFO - Capabilities {count=1, browserName=chrome, maxInstances=1, shardTestFiles=false, } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
10:55:51.750 INFO - To downstream: {"sessionId":"","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.35.528157 (4429ca2590d6988c0745c24c8858745aaaec01ef),platform=Mac OS X 10.13.2 x86_64)"}}
10:55:51.750 INFO - To downstream: {"sessionId":"","status":0,"value":null}
Starting ChromeDriver 2.35.528157 (4429ca2590d6988c0745c24c8858745aaaec01ef) on port 38981
Only local connections are allowed.
```

test steps
```
Given("I execute test",{timeout: 5 * 60 * 1000}, async function () {
    console.log(new Date().toISOString() +":"+ ' TEST EXECUTION STARTED');
    await browser.get(browser.baseUrl);
    await browser.close();
});
```

**Comment by dsolskyi** [comment]
Hello, any update on this issue?

**Comment by pawelus** [comment]
@darrinholst will you have time to look at this issue? This will hurt us all badly when control flow will be removed from Protractor later this year.

**Comment by darrinholst** [comment]
@pawelus probably not, but I'll gladly merge any PRs that resolve it

**Comment by pawelus** [comment]
@darrinholst after analysis of protractor-cucumber-framework code (not knowing how it all works yet) I have a theory that this might be because you're not waiting for the promise returned by `state.runner.afterEach()` to resolve in `setup()` (resultsCapturer.js line 51).

I'll try to test that theory after Easter (when I have something to write code on).

If that would be the case, then do you have anything against introducing some `async/await` code to the framework? It would be the easiest way to solve this but would introduce dependency on node ≥ 8.

**Comment by darrinholst** [comment]
The short version of how it works is that it hooks into protractor as a custom runner, constructs a cucumber cli command out of the given configuration and collects the results of that run however cucumber allows us to do that. cucumber < 3 was fairly easy since they gave us `registerHandler` as seen [here](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/blob/master/lib/resultsCapturer.js#L29-L33). cucumber >= 3 removed that and we had to use the event protocol formatter for this as seen [here](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/blob/master/lib/resultsCapturer.js#L35-L40).

Since these are events I don't think that waiting for the `afterEach` is going to affect anything with the run since cucumber just [emits the event](https://github.com/cucumber/cucumber-js/blob/1927e5dacd9460df9c682b32016483fed2f668ee/src/runtime/index.js#L67).

If it's just a problem with that first `afterEach` we could call it and wait at [init time](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/blob/master/index.js#L30). I'm guessing though that we'd have the same problem with each scenario since [they're not waiting either](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/blob/master/lib/resultsCapturer.js#L143). 

Sounds like we need to be using `BeforeAll` and `After` hooks.

As for `async/await` I'd like to stay at least node 6 compatible to match protractor and cucumber.

**Comment by pawelus** [comment]
You're right. Waiting for arbitrary init time works but it's just a workaround and it doesn't solve problems after scenario.

There's definitely a problem after scenario end as well as there's always a browser session left hanging after tests.

We'd need to use `BeforeAll` and `After`. But we'd have to make sure that our `After` is called after any test declared `After` to make sure there's still a browser session to be used in these test after hooks. This might be tricky as AFAIK after hooks are called in order of registration. It can't be `AfterAll` as we need this done after every scenario/example.

I still wonder why we need to call `afterEach` in `setup()` as it doesn't seem that [Jasmine](https://github.com/angular/protractor/blob/master/lib/frameworks/jasmine.js) is doing the same (it's a bit hard to understand after each hooks injection code in Protractor). One difference I noticed is that we're emitting `testPass/testFail` events after every step, but we should be doing that after scenario/example according to Protractor docs. Might this be causing the problem?

**Comment by pawelus** [comment]
Ok `After` hooks are actually called in reverse order so we should be fine there as well. So registering an `After` hook we would be the way to go here as it's guaranteed to run after all registered test `After` hooks.

Still we shouldn't need to do anything in `BeftoreAll` at all (theoretically) as it is that `afterEach` call in `setup()` that is causing problems here. It is causing Protractor to close current browser window and create a new one and not waiting for it to be created. Side effect of this (also with `SELENIUM_PROMISE_MANAGER: true`) is that any calls like `browser.window().maximize()` done in Protractor's `onPrepare` are noops when restarting between tests as first browser window is always closed before tests start.

**Comment by pawelus** [comment]
I did some more digging in Protractor code.

It is as I suspected - the fact that we emit `testPass/testFail` after each step is causing us problems here as Protractor will restart the browser on `testPass/testFail` if `afterEach()` was never called before `testPass/testFail` ( see [Protractor runner](https://github.com/angular/protractor/blob/master/lib/runner.ts) lines 17 and 40).

That's why calling `afterEach()` in setup "fixed" problems with `restartBrowserBetweenTests` as it disables browser restart on `testPass/testFail`.

The way `testPass/testFail` are emitted has to be rewritten. Those have to be emitted after scenario/example finishes and after promise returned by `afterEach()` resolves. Best would be in an After hook.

I'm not sure I'll be able to write it for all supported Cucumber versions without breaking something though.

**Comment by pawelus** [comment]
@darrinholst I've tested it and it works.

Looking at the code I have 1 doubt - you'll be flooding cucumber with `testPass/testFail` events for every step in the after hook. It is a bit against Protractor docs (they are a bit underspecified there) but they are expecting only 1 event per test.

Maybe it would be better to register the after hook only when `state.runner.afterEach` exists and emit the events from `'test-case-finished'` (in case of 3 & 4) so only 1 event is sent per test?

**Comment by pawelus** [comment]
OK now I get it. Current event model for Protractor makes sense form frameworks like Jasmine and Mocha but not much for Cucumber,

As for `state.runner.afterEach` - yes it's defined in all new versions of Protractor. Maybe we should drop all checks for this then and just assume it's there? Especially that it will be mandatory to use it starting with Protractor 6.

**Comment by arjun1092** [comment]
@darrinholst  We can we expect this as a release? This would really help me . 

Thank you for your efforts.

**Comment by nirmalcrafty** [comment]
This issue is still reproducible in v5.0.0

**Comment by dixitgargi** [comment]
Hello 
I am facing the same issue even after updating Protractor-cucumber-framework package to latest  available version.
PFB my configuaration:
    "cucumber": "^4.2.1",
    "protractor": "^5.3.2",
"protractor-cucumber-framework": "^6.0.0",

When executing multiple test scenario, after successful execution of one test scenario rest of the scenario getting failed and throwing below error:

  WebDriverError: no such session
         (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.15063 x86_64)

**Comment by dixitgargi** [comment]
I would like to re-open this issue by giving above comments

**Comment by yugandharreddygorrepati** [comment]
I am facing the same issue in protractor 5.4.0
After Browser.restart (), getting no such session error. I tried in protractor-cucumber-framework.

**Comment by yugandharreddygorrepati** [comment]
tested in cucumber 2.x,3.x,4.x and 5.x, protractor-cucumber 4.x,5.x,6.x.
Its not working.

**Comment by dixitgargi** [comment]
Hi
My issue got resolved in continous test execution 
By executing every scenarion in one webdriver session
As i am not restarting browser again
I feel its a limitation of protractor
That it does not restart webdriver for continuous execution

**Comment by dixitgargi** [comment]
Correct me if I am wrong

**Comment by yugandharreddygorrepati** [comment]
Browser. Restart is much needed especially when you run bulk scripts from Jenkins, in my case I should restart the browser after each scenario in cucumber feature due single sign on Login (SSO) mechanism. Restart works perfectly in jasmine.. But with cucumber it never works. Not sure y this ppl closed this bug without resolution. I feel ppl are re invented the wheel as WebDriver is very much robust and worked well with angular apps as well. What's new in protractor I am not understanding.
