### ISSUE TITLE
Cucumber parallel execution does not work with protractor.

### ISSUE THREAD

**Issue by mracz** [protractor-cucumber-framework/protractor-cucumber-framework#122]
Hello,

the new Cucumber 4.0 feature called parallel execution seems to not work with protractor.

When protractor start the tests we receive the error below, as many times as concurent thread we provide in the config:

`Unhandled rejection ReferenceError: element is not defined`

As Cucumber documentation explains: "Each slave is run in a separate node process".
It seems to me that protractor global is not loaded into those processes in this case.

Config:
```
exports.config = {
    specs: [
        './features/*.feature'
    ],

    directConnect: true,

    framework: 'custom',
    frameworkPath: require.resolve('protractor-cucumber-framework'),
    cucumberOpts: {
        require: ['features/**/*.js', 'pages/**/*.js'],
        format: config.e2e.cucumber.format,
        tags: getCucumberTags(),
        parallel: 2
    },
```
Extra info: 

- We are using page object pattern.
- Repro rate is 100%
- Cucumber: 4.0.0
- Protractor: 5.3.0
- protractor-cucumber-framework: 4.2.0

Thank you in advance for checking it.

**Comment by darrinholst** [comment]
I'm not sure that it's possible for this to work given protractor is the one in charge of the process(es). I'm prepared to be proven wrong though. I won't have time to investigate it myself.

What's the benefit of using cucumber's parallelization vs using protractor's sharding?

**Comment by mracz** [comment]
I'm using Protractor, Cucumber and Chrome (newest version of all) together for UI automation. I tried using protractor's sharding, but when i run the tests Chrome crashes randomly and ruin our execution (works on single thread flawlessly). 
I'm investigating this issue for 2 weeks now. I tried every kind of proposed solution without success, so I gave a try for Cucumber's parallelization without success :D 

Thanks anyway, i will report this in protractor repo.

**Comment by darrinholst** [comment]
Closing this. If anyone comes up with any ideas please reopen, but I think we're going to be better off using protractor's parallel execution/sharding instead of cucumbers since it already has all the infrastructure to handle multiple browsers.
