### ISSUE TITLE
dots followed by new line printed out in the logs when sharding

### ISSUE THREAD

**Issue by canvaspixels** [protractor-cucumber-framework/protractor-cucumber-framework#125]
resultsCapturer seems to be added as a custom cucumber formatter and prints out dots followed by new line printed out in the logs when sharding (shardTestFiles true). There doesn't seem to be a way to turn this behaviour off. Please could you add one? It makes for really messy logs. I've made a custom cucumber formatter and i'd like cucumber to handle the passes / fails, rather than protractor.

**Comment by darrinholst** [comment]
The custom formatter doesn't output anything. It is just used as a mechanism to capture the test results. I think what you're referring to is actually protractor logging the `.`s when it's running multiple processes like when sharding.

[See here](https://github.com/angular/protractor/blob/master/lib/taskRunner.ts#L92)
