### ISSUE TITLE
Cucumber is not able to separate two different string from data table 

### ISSUE THREAD

**Issue by dixitgargi** [protractor-cucumber-framework/protractor-cucumber-framework#129]
> **Description**: Login Window contain 3 main objects "username"(textbox) , "password"(textbox) and "login"(button)

> **Observation**: when running test, in username text box it is entering testtest(i.e. entering value of password in the same editbox) 

> Could you please help me with this issue as it is breaking basic functionality and it is a blocker for me to automate?

> Feature file:
```
@login
Feature: Login
    Scenario Outline: Login
    Given I launch url 
    Then I enter <username>
    Then I enter password <password>
    Then I click on login button
    Then I verify login screen
    Then I click on logOut
    Examples: 
     | username | password   |
     | test           | test        | 
```

> StepDefinetion
```
Given(/^I launch webapp url$/, function () {
    return browser.get('https://xyz.com');
    });
Then(/^I enter (.*)$/, function (username) {
        const Login = new loginPage();
        return Login.enterUserName(username);
    });
Then(/^I enter password (password)$/, function (password) {
        const Login = new loginPage();
        return Login.enterPassword(password);
        console.log('pass');
    }); 
```

**Comment by darrinholst** [comment]
@dixitgargi this framework is just the glue that allows protractor tests to be run with cucumber syntax. It appears from your description that both protractor and cucumber are working, just that behavior is not what you are expecting. You may have better luck asking questions like these through the [protractor help channels](https://github.com/angular/protractor#getting-help)
