### ISSUE TITLE
 How to use EventProtocolFormatter to call the beforeStep and afterStep in Cucumber v4?

### ISSUE THREAD

**Issue by vignesh-paramasivam** [protractor-cucumber-framework/protractor-cucumber-framework#130]
We need to log the step level info, so going through the hooks, where for the cucumber(v4.2.1) uses EventProtocolFormatter, i have tried to invoke it, but its not successful.

// support/hooks.js
const {Before, After} = require('cucumber');
const {setDefaultTimeout} = require('cucumber');

setDefaultTimeout(60000);

Before(function (scenario) {

});

// How to invoke the EventProtocolFormatter here to call the beforeStep and afterStep?
// Do we need to require and call the events in this way?
let local_event_formatter = require('../../node_modules/cucumber/lib/formatter/event_protocol_formatter.js');

After(function (scenario) {
    browser.close();
    return browser.quit();
});

**Comment by AlexandrosD** [comment]
Which protractor version are you using?

**Comment by darrinholst** [comment]
@vignesh-paramasivam is this issue specific to protractor-cucumber-framework or just a general cucumber usage question?

To use it you have to register a [custom formatter](https://github.com/cucumber/cucumber-js/blob/master/docs/custom_formatters.md#custom-formatters). When that formatter gets instantiated it will be passed an options object and on that object there is an `eventBroadcaster` property on which you can listen for the events.

As an example this library uses it [here](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/blob/master/lib/resultsCapturer.js#L54-L59).

Reopen if there was something here that you were expecting to be enhanced or fixed.
