### ISSUE TITLE
test with ambiguous and pending steps ends with exit code 0

### ISSUE THREAD

**Issue by Gordiievskyi** [protractor-cucumber-framework/protractor-cucumber-framework#131]
Hi Guys,

Same test for pure cucumber and cucumber plus protractor-cucumber-framework ends with different exit code if there is either pending or ambiguous step.

OS: Windows 10
Node: 7.8.0
protractor : 5.3.0
protractor-cucumber-framework : 5.0.0
cucumber : 4.2.1

Steps to reproduce:
1)Unpack https://www.dropbox.com/s/tonje1n3lnzi49u/test.zip?dl=0
2) Navigate to the unpacked folder
3) execute "npm install"
4)In bash cli Run command : ./node_modules/.bin/protractor protractor-conf/chrome-windows.js 
5)In bash cli After tests finished execute  echo $?
Acutal result: 0
Expected:1

Also : If you run same test but with command :  ./node_modules/.bin/cucumber-js then exit code will be 1

**Comment by darrinholst** [comment]
[v6.0.0](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/releases/tag/v6.0.0) should fix this. Thanks for the report.
