### ISSUE TITLE
Unable to generate report using protractor-multiple-cucumber-html-reporter plugin

### ISSUE THREAD

**Issue by BhargavAtyam** [protractor-cucumber-framework/protractor-cucumber-framework#132]
I am unable to generate report using protractor-multiple-cucumber-html-reporter plugin for my project.

Using the latest versions protractor : 5.3.1, Cucumber : 4.2.1 and protractor-cucumber-framework : 5.0.0 and protractor-multiple-cucumber-html-reporter : 1.7.0

Can any one help me on this. Is there any version mismatch issue as per above details.

**Comment by darrinholst** [comment]
You might have better luck opening an issue over there https://github.com/wswebcreation/protractor-multiple-cucumber-html-reporter-plugin/issues. These projects aren’t related as far as I know.

**Comment by BhargavAtyam** [comment]
Thank you for your reply darrinholst. I am already open an issue regarding this but when I am using format:json:result.json in the config file the browser immediately closes as soon as the test starts running and it shows all the test cases passed in report. 

Opened an issue in the mentioned location https://github.com/wswebcreation/protractor-multiple-cucumber-html-reporter-plugin/issues/1
