### ISSUE TITLE
process exited with error code 199

### ISSUE THREAD

**Issue by yaminir16** [protractor-cucumber-framework/protractor-cucumber-framework#133]
protractor version - 5.3.2
chrome driver - 2.40
npm - 6.1
node - 6.9.4
chrome version - 64

it says chrome version must be greater than 66.
how can i use protractor with chrome version 64?

**Comment by darrinholst** [comment]
https://stackoverflow.com/questions/50913351/e-launcher-process-exited-with-error-code-199-and-says-chrome-version-must-be
