### ISSUE TITLE
Function timed out, ensure the callback is executed within 60000 milliseconds

### ISSUE THREAD

**Issue by ebacka** [protractor-cucumber-framework/protractor-cucumber-framework#134]
**I have this stepdefinitions.js in a cucumber protractor project:**
`const assert = require('assert');
const { Given, When, Then } = require('cucumber');

var chai = require('chai');
var chaiAsPromised = require('chai-as-promised');

chai.use(chaiAsPromised);
var expect = chai.expect;

 Given('I go to {string}', {timeout: 90 * 1000},function(site) {
    browser.get(site);
    
  });

 When('I click the add button', function(task) {
  element(by.css("*[id='account-menu'] > span > span > span")).click();
  
 
  });

 Then('I should see my new task in the list', function() {
   expect(true).to.equal(true);

  });`

**And this cucmber.js file of configuration:**
`exports.config = {
  baseUrl: 'http://localhost:8080/#/',
  specs: [
    './e2e_cucumber/features/*.feature'  
  ],
  getPageTimeout: 60000,
  framework: 'custom', 
  allScriptsTimeout: 110000,
   cucumberOpts: {
    require: ['./e2e_cucumber/features/step_definitions/*.js', 'timeout.js'],  
    tags: [],                      // <string[]> (expression) only execute the features or scenarios with tags matching the expression
    strict: true,                  // <boolean> fail if there are any undefined or pending steps
    //format: ["pretty"],            // <string[]> (type[:path]) specify the output format, optionally supply PATH to redirect formatter output (repeatable)
    'dry-run': false,              // <boolean> invoke formatters without executing steps
    compiler: []                   // <string[]> ("extension:module") require files with the given EXTENSION after requiring MODULE (repeatable)
  },
  directConnect: true,

  capabilities: {
    'browserName': 'chrome'

  },

  frameworkPath: require.resolve('protractor-cucumber-framework'),

  

 onPrepare: function () {
    browser.manage().window().maximize();
  }
};`

**this is my timeout.js file included in ccumberOpts:**
`var { setDefaultTimeout } = require("cucumber");

setDefaultTimeout(5 * 1000); `

**I am getting errors of timeouts in execution:**
**× When I click the add button # e2e_cucumber\features\step_definitions\angular.js:15
       **Error: function timed out, ensure the callback is executed within 60000 milliseconds**

### **How can these timeouts be fixed?**

**Comment by darrinholst** [comment]
I think your problem is the `task` parameter in...

```
When('I click the add button', function(task) {
  element(by.css("*[id='account-menu'] > span > span > span")).click();
});
```

See the [Asynchronous - callback](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/step_definitions.md) description. Since you defined a parameter it thinks it's an async step and it waits until that parameter is called.
