### ISSUE TITLE
Test is not running

### ISSUE THREAD

**Issue by aasimali** [protractor-cucumber-framework/protractor-cucumber-framework#136]
I have set up the cucumber on my machine and trying to run the test, but, it does not work...

Here is my code...

*I am running it with Protractor*

**_conf.js_**

exports.config = {
   directConnect: true,
   framework: 'custom',
   frameworkPath: '/home/tpl/node_modules/protractor-cucumber-framework',
   capabilities: {
       'browserName': 'chrome'
   },
   cucumberOpts: {
       format: "summary"
   },
   specs: ['./*.feature']
};
__________________________

**_home.feature_**

Feature: Homepage
 
 Scenario: Visit Homepage
  Given I am on the homepage
   
________________________________

**_step.js_**

const Given = require('/home/tpl/node_modules/cucumber').Given(/^I am on the login page$/, function (callback) {
   browser.get("https://www.mysite.com/").then(function(){
     callback(); //
    })
   });

**Comment by darrinholst** [comment]
@aasimali there's not enough information here to even guess what's going on. Please see this [working example repo](https://github.com/dholst/protractor-cucumber-framework-example.git)

**Comment by aasimali** [comment]
@darrinholst - Thank you... The example is very useful.
