### ISSUE TITLE
`fail-fast` cucumberOpts working?

### ISSUE THREAD

**Issue by chrisleekr** [protractor-cucumber-framework/protractor-cucumber-framework#137]
Hi,

I am currently using protractor-cucumber-framework and try to find the way to exit the test as soon as any test failed.

I added `fail-fast` option as below to `cucumberOpts`; however, it seems not quitting the test when there is a failed test.

I also tried to find any documentation, but all I found was only a test case (https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/blob/f7895fefe404810f3d354c1bf5b1ed30bb43a122/test/cucumber1.spec.js#L28)

Am I using `fail-fast` correctly? Or is it even supported?

```
exports.config = {
...
  specs: [
    './tests/e2e/features/*.feature'
  ],
  capabilities: {
    'browserName': 'chrome',
    'shardTestFiles': true,
    'maxInstances': 4,
    'chromeOptions': {
      'args': ['--no-sandbox', '--disable-gpu', '--start-maximized']
    }
  },
...
cucumberOpts: {
    require: ['./tests/e2e/features/step_definitions/**/*.ts'],
    strict: true,
    dryRun: false,
    compiler: [],
    format: 'json:./tests/output/e2e-result/results.json',
    'fail-fast': true,
    defaultTimeout: 10000
  },
...
```

**Comment by darrinholst** [comment]
@chrisleekr When you're sharding each process is its own separate instance of cucumber so it will fail fast only in that one shard. The rest of them don't have any idea about each other since protractor is in charge of the process orchestration.

**Comment by chrisleekr** [comment]
Thanks, @darrinholst 

Then is there any way I can make test stop even use of sharding test files when any of test cases fail?

**Comment by darrinholst** [comment]
Nothing that I'm aware of. There was this old [protractor issue](https://github.com/angular/protractor/issues/499) asking for it, but I think it was decided to push that off to the test runner. You could try some kind of global state check in a an After hook.

**Comment by chrisleekr** [comment]
I see. Well, if there is no, nothing I can do at the moment. 

I will try with global state check later.


Thanks, @darrinholst
