### ISSUE TITLE
WebDriverError: no such session ((Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.15063 x86_64))

### ISSUE THREAD

**Issue by dixitgargi** [protractor-cucumber-framework/protractor-cucumber-framework#138]
> I am facing the below issue When executing multiple test scenario, after successful execution of one test scenario rest of the scenario getting failed and throwing below error:

` × Given I launch webapp url # test\features\step_definitions\actionsteps.js:32
       WebDriverError: no such session
         (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.15063 x86_64)
`

> PFB package.json:
> "cucumber": "^4.2.1",
> "protractor": "^5.3.2",
> "protractor-cucumber-framework": "^6.0.0",

`// conf.js
exports.config = {
  framework: 'custom',
  seleniumAddress: 'http://localhost:4444/wd/hub',
  frameworkPath: require.resolve('protractor-cucumber-framework'),
  ignoreUncaughtExceptions: true,
  specs: [
    'test/features/*.feature' // accepts a glob
  ],

  onPrepare: () => {
    browser.driver.manage().deleteAllCookies();
    browser.manage().window().maximize(); //maximize the browser before executing the feature files
  },
  // rootElement: 'div#nested_ngcontent',
  useAllAngular2AppRoots: true, 
  cucumberOpts: {
    plugin: "pretty",
    timeout: '10000',
    monochrome: "true",
    // require step definitions
    require: [
     'customConfig.js' ,'test/features/step_definitions/actionsteps.js' // accepts a glob
    ],
    tags:['@Adminregression'], 
  strict: true,                  // <boolean> fail if there are any undefined or pending steps
  'dry-run': false,              // <boolean> invoke formatters without executing steps
  format: ['json:reports/reports.json'],
  compiler: []
  },
  plugins: [{ 
    package: 'protractor-multiple-cucumber-html-reporter-plugin', 
    options:{ 
    // read the options part for more options 
    automaticallyGenerateReport: true, 
    removeExistingJsonReportFile: true 
    } 
    }],
  capabilities: {
    'elementScrollBehavior': 1,
    'browserName': 'chrome'
    },
  chromeOnly: true,
}`

**Comment by lakshmi-236** [comment]
It may be the issue with your test cases, please check the test case which got pass and confirm things like usage of done() missing brakes in switch cases etc.

**Comment by dixitgargi** [comment]
Actually I got to know that when I am running one scenario which includes steps as (launching browser,  then some action and then closing browser by Browser.close() method) and when next scenario is getting picked up for the execution it is throwing me error. so does that mean **"Protractor does not allow closing of browser in between multiple scenarios execution?"** as closing browser will tend to shut down webdriver as well

**Comment by AlexandrosD** [comment]
Closing as obsolete, almost a year passed since this was opened. Please reopen if issue persists.
