### ISSUE TITLE
Parallel execution in protrctor- cucumber

### ISSUE THREAD

**Issue by lakshmi-236** [protractor-cucumber-framework/protractor-cucumber-framework#139]
I am having 5 feature files of different lengthand totally 60 scenarios are there.  I want to execute 5 instances with 12 scenarios in each. Is it possible?

**Comment by darrinholst** [comment]
No, it's not possible natively with protractor since it shards by file. It is possible using multi capabilities and splitting them up yourself. An example can be found [here](https://github.com/darrinholst/protractor-cucumber-example/blob/master/protractor.conf.js#L15-L47)

**Comment by lakshmi-236** [comment]
when spec is given inside multicapabilities,same test case  is executed multiple times, how to resolve his issue?

**Comment by darrinholst** [comment]
You're not supposed to have the same spec in there multiple times if you're using it for the purpose of sharding. Also I noticed that example above doesn't split the scenarios up evenly. [This one does](https://gist.github.com/darrinholst/bd00aa0f40d5978a84c47b012215b080)

**Comment by lakshmi-236** [comment]
Tried with above one also, still the same issue exists. i have not given same spec multiple times. Given it same as that of the example.

**Comment by darrinholst** [comment]
If you run it with the `DEBUG=protractor-cucumber-framework` environment variable set it will show the command that is being run. That should help you track the issue down.

**Comment by Izhaki** [comment]
Here's a more up to date example of how to get this working:

https://github.com/gd46/dibellag-automation-framework/blob/master/configuration.js

I have to change a few things (eg, add `order: 'defined'` to the `getTestCasesFromFilesystem` call), but it did work eventually.
