### ISSUE TITLE
Can Protractor handle window authentication pop up?

### ISSUE THREAD

**Issue by dixitgargi** [protractor-cucumber-framework/protractor-cucumber-framework#140]
Hello,

I am facing one issue in my application where I am getting window authentication pop up. will it be possible to handle these popups through protractor-cucumber framework? or do I need to integrate this framework with robot js?

**Comment by darrinholst** [comment]
@dixitgargi this is probably a better question for protractor. This library is just the glue that allows protractor tests to be run with cucumber syntax.
