### ISSUE TITLE
I am not able to select multiple checkbox on a webpage. working upon protractor and cucumber framework

### ISSUE THREAD

**Issue by dixitgargi** [protractor-cucumber-framework/protractor-cucumber-framework#141]
I have to perform check and un-check operation upon multiple checkboxes present on a webpage. check boxes are divided into categories within an accordion. There are multiple accordion, once clicked upon each accordion, select all check box are present in those accordion.

`selectAllCheckbox () {
    console.log('checkbox');
    var allAccordion, allCheckbox;
    allAccordion = element.all(by.id(`accordion`));
    allCheckbox = element.all(by.xpath(`//*[@type="checkbox"]`));
    allAccordion.each(function(links) {
        allAccordion.getText(links);
        console.log(links);
    }).then(function(links) {
        for (var i = 0;i < links.length;i++) {
            links.click();
            console.log('accordion clicks')
            browser.sleep(20000);
            allCheckbox.click();
            browser.sleep(20000);
        }
    })
};`

**Comment by darrinholst** [comment]
@dixitgargi please try stackoverflow for this type of question. This library just allows running of protractor tests with cucumber syntax. If I would have to guess you're probably not waiting for those asynchronous actions to finish in your step.
