### ISSUE TITLE
Hanging Webdriver instance with progress-bar formatter, protractor's parallelization and failed test

### ISSUE THREAD

**Issue by Teddy34** [protractor-cucumber-framework/protractor-cucumber-framework#142]
Hi guys,

I've got an issue with protractor parallelization and the Cucumber framework when using the `progress-bar` formatter.
If all tests succeed, the Webdriver instance is correctly released. If one test fails, the Webdriver instance is never released and the report never printed. If the `progress` formatter is selected, there's no issue.

Here's a repo with the minimal configuration to make it fail: https://github.com/Teddy34/protractor-cucumber-issue

**Comment by Teddy34** [comment]
Closing because it's more a cucumber issue than protractor-cucumber-framework one.

**Comment by Teddy34** [comment]
Related to https://github.com/cucumber/cucumber-js/issues/982

**Comment by darrinholst** [comment]
@Teddy34 thanks for the repo...it definitely helps. Unfortunately I don't *think* this is related to anything this library is doing (or more importantly can do to fix it). I looked into how the progress-bar formatter works and it uses the [node-progress](https://github.com/visionmedia/node-progress). That might be doing something to cause it to hang in relation to how protractor is capturing stderr when running parallel processes.

**Comment by lukaslewandowski-pearson** [comment]
Thank You for reporting this :)

**Comment by AlexandrosD** [comment]
Closing as unrelated to this framework.
