### ISSUE TITLE
Multiple Step definition file path to be configure  in config file in protractor-cucumber framework

### ISSUE THREAD

**Issue by dixitgargi** [protractor-cucumber-framework/protractor-cucumber-framework#143]
I would like to have separate step definition files for different feature file. so Do I need to declare step definition files path under `Suit` option?

**Comment by tuna0909** [comment]
Hi @dixitgargi , you should change your config like this:
cucumberOpts: {
        require: [
            '../stepDefinitions/*.js'
        ]
    }

it will run all .js files in stepDefinitions

**Comment by darrinholst** [comment]
Thanks for the reply @tuna0909. 

These questions are probably better suited for stackoverflow.
