### ISSUE TITLE
cucumber 5.0.0

### ISSUE THREAD

**Issue by rolaveric** [protractor-cucumber-framework/protractor-cucumber-framework#145]
cucumber 5.0.0 has been released:
https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md#500-2018-04-09

Using it with protractor-cucumber-framework raises a "We don't support cucumber version 5" error from `resultsCapturer.js`.

The breaking version bump appears to be solely about dropping support for Node v4.
So there doesn't appear to be any change required except to add a `case 5:` fallthrough with `case 4:`.

**Comment by darrinholst** [comment]
Thanks for the report. This should be addressed in v6.1.0.
