### ISSUE TITLE
WebDriverError no such session error while using scenario outline

### ISSUE THREAD

**Issue by bitquality** [protractor-cucumber-framework/protractor-cucumber-framework#146]
Hi,

When i use scenario outline then the only the first record in my examples data set gets executed and the second row onwards it keeps failing with "WebDriverError no such session". And can i set default options for cucumber to not to quit the browser after execution or launch a new browser window to run the next scenario without using hooks from cucumber options?

```
Scenario Outline:  User login

    Given the user is on Login Page
    And   the users enter "<username>" and "<password>" 
       
   Examples:
   | username| password|
   | User_1  | passw123|
   | User_2  | passw123|
```

```
After(async function(scenario) {
  if (scenario.result.status === Status.FAILED) {
    // screenShot is a base-64 encoded PNG
    // const screenShot = await browser.takeScreenshot();
    // this.attach(screenShot, 'image/png');
    console.log('\n Scenario Completed: ', scenario.pickle.name);
  } else if (scenario.result.status === Status.PASSED) {
    console.log('\n Scenario Completed: ', scenario.pickle.name);
  }
  await browser.close();
});
```

And below are my cucumber options.

```
exports.config = {
  seleniumAddress: 'http://localhost:4444/wd/hub',
  specs: ['./e2e/features/*.feature'],
  capabilities: {
    browserName: 'chrome',
    chromeOptions: {
      args: ['--disable-extensions'],
    },
    maxInstances: 1,
  },

  framework: 'custom',
  frameworkPath: require.resolve('protractor-cucumber-framework'),

  cucumberOpts: {
    require: ['./e2e/steps/*.ts', './e2e/support/*.ts'],
    tags: ['@smoke'],
    strict: true,
    format: [
      // 'pretty',
      // 'pretty: reports/summary.txt',
      // 'json: reports/summary.json'
    ],
    dryRun: false,
    compiler: [],
    'fail-fast': false,
    defaultTimeoutInterval: 160 * 1000,
  },
  baseUrl: 'http://localhost:8082/',

  onPrepare() {
    require('ts-node').register({
      project: './e2e/tsconfig.e2e.json',
    });
    browser.manage().deleteAllCookies();
  },

  resultJsonOutputFile: './e2e/reports/report.json',
  getPageTimeout: 1000 * 1000,
  allScriptsTimeout: 5000 * 1000,
  ignoreUncaughtExceptions: true,
};

```

And i set ignoreUncaughtExceptions to true so that execution will continue even if there are NoSuchElementError. But when i read this the Scenario.result.status in after hook block , it returns as PASSED. I kept fail-false also to true the so that it can continue executing rest of the steps in cucumber scenario.

It works fine for regular scenarios.

Krishna

**Comment by pawelus** [comment]
Why do you have `await browser.close()` in your afterhook?

You're destroying your session after first test with that

**Comment by bitquality** [comment]
I wanted to run each test on a new window.

**Comment by pawelus** [comment]
Protractor has a "restart browser between tests" capability for this (check their dics for the exact name).

**Comment by bitquality** [comment]
One ptor step had return statement missing and it skips rest of the steps..
