### ISSUE TITLE
browser.restart gives me an error "NoSuchSessionError" after restart

### ISSUE THREAD

**Issue by yugandharreddygorrepati** [protractor-cucumber-framework/protractor-cucumber-framework#147]
Steps :
browser.get(url);
browser.restart();
browser.get(url);

Getting below error :-
This driver instance does not have a valid session ID (did you call WebDriver.quit()?) and may no longer be used.
NoSuchSessionError: This driver instance does not have a valid session ID (did you call WebDriver.quit()?) and may no longer be used.

Its reproducible in all the version of cucumber, protractor-cucumber

Protractor : 5.3 or 5.4
Cucumber :- 2.x,3.x,4.2.1, 5.0.1
Protractor-cucumber - 4.x,5.0.0 , 6.1.1
Node :- 6.11

**Comment by darrinholst** [comment]
You might want to try waiting for the promises returned as shown in the [documentation](https://www.protractortest.org/#/api?view=ProtractorBrowser.prototype.restart). I can't remember if control is enabled or not. If it is you could also use [restartSync](https://www.protractortest.org/#/api?view=ProtractorBrowser.prototype.restartSync)

**Comment by AlexandrosD** [comment]
Closing as obsolete. Please reopen if issue persists.

**Comment by techshashank80** [comment]
Hi, 
Still, this issue exists. 

Protractor :  5.4.2
Cucumber :- 5.1.0
Protractor-cucumber - 6.1.3
Node :- 10.15.1
npm@6.4.1
