### ISSUE TITLE
protractor-cucumber-framework expect is not working

### ISSUE THREAD

**Issue by wattle9** [protractor-cucumber-framework/protractor-cucumber-framework#151]
I am using protractor-cucumber-framework and tried below code snippet.

```
var {defineSupportCode} = require('cucumber');
var chai = require('chai');
var chaiAsPromised = require('chai-as-promised');
chai.use(chaiAsPromised);
var expect = chai.expect;

defineSupportCode(function ({And, But, Given, Then, When}) {

    Given(/^I launch Chrome browser$/, function () {
      browser.get('http://www.angularjs.org');
     expect(element(by.id('the-basics')).getText()).to.eventually.equal('The basics');
}
}
```

When I execute the script, I can see it is passing. Even if I use wrong element ID as well, the script is passing.
` expect(element(by.id('theyyy-basics')).getText()).to.eventually.equal('The kkkbasics');`

Is this an issue with protractor-cucumber-framework??

**Comment by kacpe-r** [comment]
That's not a protractor cucumber available formats issue. Add `return` before expect.

**Comment by darrinholst** [comment]
@kacpe-r is correct you need to return the promise so cucumber knows to wait for it, otherwise the step will end without ever asserting anything
