### ISSUE TITLE
No element found using locator: By(css selector, *[id=

### ISSUE THREAD

**Issue by wattle9** [protractor-cucumber-framework/protractor-cucumber-framework#152]
Hi, I thought of reporting this issue as I am not sure whether it is due to my coding / Protractor issue.
 
I am using Protractor-Cucumber frame work and have written code modules to send user name and password to below login page.
 
https://www.tutorialspoint.com/angularjs/src/login/index.html#/login

I have attached the source of the page to show element names.

<img width="1138" alt="screen shot 2018-10-15 at 2 43 52 pm" src="https://user-images.githubusercontent.com/43224329/46929964-7ca63180-d08e-11e8-9f84-3f2ef8a6fcdf.png">

 
Whenever, I tried to execute, I get below error.As per the login page source element names and modules are clear. Not, sure what is causing this. Any help is appreciated. 
 
E/launcher - No element found using locator: By(css selector, *[id="username"]) 
E/launcher - NoSuchElementError: No element found using locator: By(css selector, *[id="username"])

Login Page object
———————————————————————————
```
var LoginPage = function() {
    var username = element(By.id('username'));
    var password = element(By.id('password'));
    var loginform = element(By.id('form'));


    this.loadpage = function(site) {
        browser.ignoreSynchronization = true;
        browser.get(site);

    };

    this.setUserName = function(name) {
        username.sendKeys(name);
    };

    this.setPassword = function(pwd) {
        password.sendKeys(pwd);
    };

    this.login = function() {
        loginform.submit();
    };
};
module.exports = new LoginPage();
```

Login.JS
———————————————————————————

> 
> var {setDefaultTimeout} = require('cucumber');
> var {defineSupportCode} = require('cucumber');
> setDefaultTimeout(60 * 1000);
> var LoginPage = require('../../PageObjects/loginPage.js');
> var chai = require('chai');
> var chaiAsPromised = require('chai-as-promised');
> 
> chai.use(chaiAsPromised);
> var expect = chai.expect;
> 
> defineSupportCode(function ({And, But, Given, Then, When}) {
> 
>     Given(/^I login into tutorialpoint"$/, async () => {
>         await  LoginPage.loadpage('https://www.tutorialspoint.com/angularjs/src/login/index.html#/login');
> 
>     },50000);
> 
>     When(/^I enter "([^"]*)" as user name$/, async (arg1) => {
>         await LoginPage.setUserName(arg1);
> 
>     });
>     When(/^I enter "([^"]*)" as password$/, async (password) => {
>        await LoginPage.setPassword(password);
> 
>     });
>     When(/^I click login button$/, async () => {
>         LoginPage.login();
> 
> 
>     });
> 
> 
> });
>

**Comment by rabindranathfv** [comment]
i have similar issue but in your case i think if you use in Given and when u must use await in your main script if you are using asyc methods (node v8.x.x or higher ) because the control flow for async/await operations is different

**Comment by pawelus** [comment]
@wattle9 all your functions using Protractor actions have to be asynchronous and await for those actions as well, e.g.:
```
this.loadpage =  async function(site) {
        browser.ignoreSynchronization = true;
        await browser.get(site);
};
```
Because right now you're not waiting for all those async actions to complete.

Also, why are you turning synchronization off? You're loosing all the benefits of Protractor this way.
