### ISSUE TITLE
trouble with not tags

### ISSUE THREAD

**Issue by gforceg** [protractor-cucumber-framework/protractor-cucumber-framework#153]
By default, all of my feature scenarios are tested in the browser. Scenarios not tested in the browser are tagged `@nonbrowser`.

This tag isn't working: 
```javascript
tags: ['not @nonbrowser']
```
I looked at index.js and [it looks to me](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/blob/master/index.js#L127) like `~@nonbrowser` is supposed to be equivalent to `not @nonbrowser` but when I try using `~@nonbrowser` cucumber only targets scenarios tagged `@nonbrowser`.

I am trying to follow the cucumber tag expressions [doc](https://docs.cucumber.io/cucumber/api/#tag-expressions). Is `not @nonbrowser` supported am I doing this wrong?

**Comment by darrinholst** [comment]
@gforceg can you try running with DEBUG=protractor-cucumber-framework and see if the actual cucumber call looks correct?

**Comment by gforceg** [comment]
The default profile in cucumber.js was interfering with the configuration in protractor.conf.js.
I had to remove the tags from the default profile and now it works.
