### ISSUE TITLE
Error: Cannot find module 'pretty'

### ISSUE THREAD

**Issue by djom20** [protractor-cucumber-framework/protractor-cucumber-framework#154]
Hi there,

I just update the `cucumber` and `protractor-cucumber-framework` version to the latest version, so now I'm facing this bug. Before the updated I was using format with `pretty` option and now when I try to run the tests I'm getting that it's not possible found the `pretty` module. So I need to show the `Gherkin` steps and not the dots style.

protractor: 5.4.1
cucumber: 5.0.2
protractor-cucumber-framework: 6.1.1

![image](https://user-images.githubusercontent.com/1834808/48211184-f3a9af80-e346-11e8-9070-1a7a21aef23d.png)

```
'use strict';

exports.config = {
    directConnect: true,
    ignoreUncaughtExceptions: true,
    baseUrl: `${baseUrl}/app/index.html#`,
    capabilities: {
        'browserName': 'chrome',
        'name': 'Test',
        'chromeOptions': {
            'args': [],
            'prefs': {
                'profile.managed_default_content_settings.notifications': 1
            }
        }
    },

    specs: [path.join(__dirname, '..', '..', 'features', '**', '*.feature')],

    allScriptsTimeout: 500000,

    framework: 'custom',
    frameworkPath: require.resolve('protractor-cucumber-framework'),
    cucumberOpts: {
        require: [
            path.join(__dirname, '..', '..', 'step_definitions', '**', '*_steps.js')
        ],
        format: ['pretty'], // here is the bug
        tags: ['@complete']
    }
};
```

Is there any solution for that?

**Comment by darrinholst** [comment]
That formatter was removed in cucumberjs version 3. [changelog](https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md#300-2017-08-08)

**Comment by djom20** [comment]
Okay great for that @darrinholst but how I can show the gherkin style?

**Comment by darrinholst** [comment]
Any errors show the gherkin by default. There is nothing built in to do it anymore. There may be someone that built a replacement if you look around, but I don’t know.
