### ISSUE TITLE
Next Test Case is not getting executed, when pervious test case fails due to assertion

### ISSUE THREAD

**Issue by anindyaspatra** [protractor-cucumber-framework/protractor-cucumber-framework#156]
I am running two Test Cases in Protractor Cucumber framework, but when the First Test Case fails due to Assertion,(i.e. actual value is not matching with the expected value.) the execution of the next test case stops. I am not able to execute the second test case and the browser is getting closed

**Comment by darrinholst** [comment]
Can you post your config and the output?

**Comment by darrinholst** [comment]
reopen with the config and output if this is still a problem
