### ISSUE TITLE
No colors in CLI after updating cucumber to 5.0.3

### ISSUE THREAD

**Issue by lukaslewandowski-pearson** [protractor-cucumber-framework/protractor-cucumber-framework#157]
I just updated Cucumber to 5.0.3 and colors from CLI was removed, is there some way to force them back?

Can I somehow pass: --format-options '{"colorsEnabled": true}' to the  cucumberOpts object?
(in this object I already have "format" array).

**Comment by darrinholst** [comment]
From the [docs](https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#colors) it looks like you have to explicitly turn them off, not turn them on. I'm not sure tbh. You can try...

``` js
cucumberOpts: {
  'format-options':  '{"colorsEnabled": true}',
  // ...
}
```

...and see what happens.
