### ISSUE TITLE
Failed steps are emitted as passed

### ISSUE THREAD

**Issue by segrey** [protractor-cucumber-framework/protractor-cucumber-framework#158]
Example project: https://github.com/segrey/angular-protractor-cucumber

An inline plugin is declared in protractor.conf.js:
```
  plugins: [{
    inline: {
      postTest: function(passed, testInfo) {
        console.log();
        console.log(JSON.stringify(testInfo) + ", passed: " + passed);
        console.log();
      }
    }
  }],
```

1. Run `protractor --baseUrl https://angular.io`
2. Output will contain 3 passed tests:
```
{"name":"Given I am on the angular.io site","category":"Search: Type in a search-term","durationMillis":1,"sourceLocation":{"filePath":"e2e/features/search.feature","line":7,"column":5},"progress":{"step":1,"steps":3}}, passed: true


{"name":"When I type \"foo\" into the search input field","category":"Search: Type in a search-term","durationMillis":1746,"sourceLocation":{"filePath":"e2e/features/search.feature","line":8,"column":5},"progress":{"step":2,"steps":3}}, passed: true


{"name":"Then I should see some results in the search overlay","category":"Search: Type in a search-term","durationMillis":1170,"sourceLocation":{"filePath":"e2e/features/search.feature","line":9,"column":5},"progress":{"step":3,"steps":3}}, passed: true

```

However, `Search: Type in a search-term` -> `Then I should see some results in the search overlay` is failed.

Is it possible to emit correct events? For example, IntelliJ IDEs rely on these events to build the test tree, as a result failed steps are shown green: https://youtrack.jetbrains.com/issue/WEB-36321.

**Comment by darrinholst** [comment]
I'd start with some `console.log`s or breakpoints [here](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/blob/master/lib/resultsCapturer.js#L155) to figure out where it's going wrong. I'm guessing something changed in the status where we're not falling into any of the cases [here](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/blob/master/lib/resultsCapturer.js#L229). I'm pretty sure this used to work with older versions of cucumber.

**Comment by segrey** [comment]
Unfortunately, the issue is still reproduced with protractor-cucumber-framework updated to the latest version (6.2.0 as of now).
@AlexandrosD Should we re-open the issue?

**Comment by bashjs** [comment]
This one may be related: https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/issues/179

**Comment by dlarr** [comment]
I am experiencing same issue.

Please reopen or give a workaround ?

![image](https://user-images.githubusercontent.com/2865021/73534292-111dda00-4421-11ea-9b14-aa8d84454c76.png)
