### ISSUE TITLE
E/launcher - Error: TypeError: require(...).run is not a function

### ISSUE THREAD

**Issue by aman-daharwal** [protractor-cucumber-framework/protractor-cucumber-framework#160]
Description : I am trying to launch a simply launch a browser using protractor-cucumber and I am getting error as `E/launcher - Error: TypeError: require(...).run is not a function`

Below is my config file

```
exports.config = {
    seleniumAddress: 'http://127.0.0.1:4444/wd/hub',
    getPageTimeout: 60000,
    allScriptsTimeout: 500000,
    framework: 'custom',
    // path relative to the current config file
    frameworkPath: require.resolve('protractor-cucumber'),
    //frameworkPath: 'node_modules/protractor-cucumber',
    capabilities: {
        'browserName': 'chrome'
    },
   
    // Spec patterns are relative to this directory.
    specs: [
        'features/*.feature'
    ],
    baseURL: 'http://localhost:8080/',
    cucumberOpts: {
        require: 'features/step_definitions/stepdefs.js',
        tags: false,
        format: 'pretty',
        profile: false,
        'no-source': true
    }
};
```

Environment info :
    "cucumber": "^5.1.0",
    "framework": "0.0.0",
    "protractor": "^5.4.2",
    "protractor-cucumber": "^0.1.8"

Actual Result : Browser is launching for a second and gets killed automaticallya nd the above error is thrown.

Error Stack trace : 

> C:\Users\adaharwa\WebstormProjects\Sample>protractor config.js
> [11:30:06] I/launcher - Running 1 instances of WebDriver
> [11:30:06] I/hosted - Using the selenium server at http://127.0.0.1:4444/wd/hub
> [11:30:09] E/launcher - Error: TypeError: require(...).run is not a function
>     at q.then.then.then.then (C:\Users\adaharwa\WebstormProjects\Sample\node_modules\protractor\built\runner.js:405:43)
>     at _fulfilled (C:\Users\adaharwa\WebstormProjects\Sample\node_modules\q\q.js:834:54)
>     at C:\Users\adaharwa\WebstormProjects\Sample\node_modules\q\q.js:863:30
>     at Promise.promise.promiseDispatch (C:\Users\adaharwa\WebstormProjects\Sample\node_modules\q\q.js:796:13)
>     at C:\Users\adaharwa\WebstormProjects\Sample\node_modules\q\q.js:556:49
>     at runSingle (C:\Users\adaharwa\WebstormProjects\Sample\node_modules\q\q.js:137:13)
>     at flush (C:\Users\adaharwa\WebstormProjects\Sample\node_modules\q\q.js:125:13)
>     at process._tickCallback (internal/process/next_tick.js:172:11)
> [11:30:09] E/launcher - Process exited with error code 100

**Comment by darrinholst** [comment]
Hi @aman-daharwal, It looks like you are installing a different library than this one...

`"protractor-cucumber": "^0.1.8"`

This one is called `protractor-cucumber-framework`
