### ISSUE TITLE
In Cucumber, callback function getting timedout though callback is called. Already increased DefaultTimeout but still error

### ISSUE THREAD

**Issue by mohitgarg1522** [protractor-cucumber-framework/protractor-cucumber-framework#161]
Below is the Cucumber Given Step definition and in this callback() function was hit successfully and was able to see the console line i.e. "This is a callback function"
`const assert = require('assert')
const {
	Before,
	Given,
	When,
	Then
} = require('cucumber');

var {
	setDefaultTimeout
} = require('cucumber');

setDefaultTimeout(6 * 1000);

Given('This has only one word {string}', function (string, callback) {
	console.log(string);

	function callback() {}
	callback();
});`
But this step is not getting terminated, throws error "function timed out, ensure the callback is executed within 6000 milliseconds"
`C:\Users\Mohit.Garg\Desktop\Cucumber practice\example5>protractor conf.js
[17:14:55] I/launcher - Running 1 instances of WebDriver
[17:14:55] I/local - Starting selenium standalone server...
[17:14:57] I/local - Selenium standalone server started at http://10.200.3.79:55733/wd/hub
(node:27784) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Feature: Login

  Scenario: Login
    Given This has only one word "hi"
This is a callback function
    × failed
      Error: function timed out, ensure the callback is executed within 6000 milliseconds
          at Timeout._onTimeout (C:\Users\Mohit.Garg\Desktop\Cucumber practice\example5\node_modules\cucumber\src\user_code_runner.js:61:18)
          at ontimeout (timers.js:436:11)
          at tryOnTimeout (timers.js:300:5)
          at listOnTimeout (timers.js:263:5)
          at Timer.processTimers (timers.js:223:10)`
I don't think this is related to DefaultTimeout becasue if I use below code with same Timeout value it runs perfectly. I have replaced "callback" in Given with different name "newcallback" and called inside callback function at the end. See below
`Given('This has only one word {string}', function (string, newcallback) {
	console.log(string);

	function callback() {
		newcallback()
	}
	callback();
});`
I hope am clear with my issue, your help is very much appreciated.

**Comment by sri85** [comment]
There are couple of ways you could callback in your cucumber step
The first one would be 
```
 Given(/^I do something$/, function (callback) {
// do something here
        callback();
    });
```
else you could also do something like
```
Given(/^I do something$/, function () {
        return <some_assertion>.
    });
```
