### ISSUE TITLE
Scenarios with skipped steps are marked as passed

### ISSUE THREAD

**Issue by dbarbuzzi** [protractor-cucumber-framework/protractor-cucumber-framework#165]
Per the [Cucumber.js documentation](https://github.com/cucumber/cucumber-js/blob/3.x/docs/support_files/step_definitions.md#skipped-steps), if a scenario’s step is skipped then (a) all subsequent steps in that scenario should be skipped and (b) the scenario’s status result for the run is ‘skipped’.

In practice, this behaves as expected when running tests directly with Cucumber.js, but when running with protractor via the protractor-cucumber-framework, the same set of tests yields an overall end result for the scenarios as ‘passed’.

I initially discovered this with somewhat dated versions of all related tools (protractor, protractor-cucumber-framework, cucumber.js), however, I have reproduced the behavior with the latest versions of all related tools in a minimal set of files here:

https://gist.github.com/dbarbuzzi/aca43fa106139c76ecc95ae8570cf9f9

It is a combination of the sample Cucumber.js code (with one additional line to mark a step as skipped) as well as a very basic config adaptation from the protractor-cucumber-framework config sample (folder structure is noted in the top comment of source code files).

Based on that gist, there are two npm run scripts which produce the following results:

```sh
# running the tests directly with cucumber.js
$ npm run test:cucumber

> cucumber-skips@1.0.0 test:cucumber /Users/barbuzzid/Dev/bugreports/cucumber-skips
> cucumber-js

.--.--.--.--

4 scenarios (4 skipped)
12 steps (8 skipped, 4 passed)
0m00.002s

# running the tests with protractor
$ npm run test:protractor

> cucumber-skips@1.0.0 test:protractor /Users/barbuzzid/Dev/bugreports/cucumber-skips
> protractor protractor.config.js

[15:37:15] I/launcher - Running 1 instances of WebDriver
[15:37:15] I/local - Starting selenium standalone server...
[15:37:16] I/local - Selenium standalone server started at http://172.25.0.151:50606/wd/hub
.--..--..--..--.

4 scenarios (4 passed)
12 steps (8 skipped, 4 passed)
0m00.001s
[15:37:18] I/local - Shutting down selenium standalone server.
[15:37:18] I/launcher - 0 instance(s) of WebDriver still running
[15:37:18] I/launcher - chrome #01 passed
```

Looking at the dots/dashes in the output, I suspect there is an `After` hook being injected that is ultimately causing the problem with the scenario being incorrectly marked as ‘passed’.

**Note:** I’ve attached a ZIP here which is the same contents as the Gist except it preserves the directory structure so it’s a bit easier to use – just install the dependencies and then you should be good to go with running the two noted npm scripts.

[cucumber-skips.zip](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/files/3139750/cucumber-skips.zip)

**Comment by dbarbuzzi** [comment]
A quick addition; it appears this is at least in part related to default Cucumber.js behavior for which I have also created an issue: cucumber/cucumber-js#1200

Ideally, I think it would make the most sense for the root default behaviors to change in Cucumber.js, but as an alternative, it may make sense that a workaround would be that after hooks return the same status of the scenario they are following _when they otherwise complete successfully_. Therefore, if such a workaround is acceptable for this project, the injected hook could return the `scenario.result.status` value from the `scenario` argument that it can accept.

**Comment by AlexandrosD** [comment]
Fixed by https://github.com/cucumber/cucumber-js/pull/1162
