### ISSUE TITLE
browser.restart is not working between scenarios and features 

### ISSUE THREAD

**Issue by techshashank80** [protractor-cucumber-framework/protractor-cucumber-framework#167]
Hi There,

While running before and after hook, getting the following error:
**NoSuchSessionError: This driver instance does not have a valid session ID (did you call WebDriver.quit()?) and may no longer be used.**

Before hook:
broswer.get("https://sampleurl");

After hook:
broswer.close();
broswer.restart();

Package:

Protractor: 5.4.2
Cucumber:- 5.1.0
Protractor-cucumber - 6.1.3
Node:- 10.15.1

I know the fix is not available right now, is there any temp workaround which I could use?

Thanks
Shashank

**Comment by pawelus** [comment]
`restartBrowserBetweenTests` from Protractor config not working for you?

Are you waiting for promises to resolve correctly? From your description I'd assume you don't and that's the root of your problems.

**Comment by techshashank80** [comment]
In both cases(Broweser.Restart/restartBrowserBetweenTests ) , i am getting the same error:
      NoSuchSessionError: This driver instance does not have a valid session ID (did you call WebDriver.quit()?) and may no longer be used.

Yes, I am waiting for promises to resolve correctly.

**Comment by AlexandrosD** [comment]
As mentioned above, not related to this package.
