### ISSUE TITLE
Test steps are not executed when format is specified in cucumber options

### ISSUE THREAD

**Issue by sudhu678** [protractor-cucumber-framework/protractor-cucumber-framework#168]
When I comment out the format cucumber option, test steps are executed. If I specify format, test steps are not executed. I need to specify format to generate report using third party plugins.

Here are my configurations:

* protractor-multiple-cucumber-html-reporter: 1.8.1
* Node.js version: 11.5.0
* NPM version: 6.4.1
* Platform name and version: Mac High Sierra, 10.13.6
* protractor version: 5.4.2
* Cucucmber version: 1.3.1
* protractor-cucumber-framework version: 6.1.3
Config of protractor + protractor-multiple-cucumber-html-reporter
exports.config = { seleniumAddress: 'http://127.0.0.1:4444/wd/hub', framework: 'custom', frameworkPath: require.resolve('protractor-cucumber-framework'), capabilities: { 'browserName': 'chrome' },
specs: [
    'features/login.feature'
],

cucumberOpts: {
     require: './steps/login.js',
     format: 'json:.tmp/results.json'
},
plugins:[{
    package: 'protractor-multiple-cucumber-html-reporter-plugin',
    options:{
        automaticallyGenerateReport: true,
        removeExistingJsonReportFile: true
    }
}]
};

**Comment by dsamburskyi** [comment]
@sudhu678 Not sure if this is still relevant for you.
Try to define formatters as an array, like
```
format: ['json:.tmp/results.json']
```
You can pass multiple formatters to Cucumberjs as an array.

**Comment by sudhu678** [comment]
I am closing this defect. Test steps were taking more than cucumber default timeout. After increasing the default timeout, it worked.
