### ISSUE TITLE
Framework takes Cucumber Before hook result and reports it as a first scenario step result

### ISSUE THREAD

**Issue by bashjs** [protractor-cucumber-framework/protractor-cucumber-framework#179]
In cases, when Cucumber steps have `Before` hooks, `protractor-cucumber-framework` reports wrong steps as passed. As a result, failing tests may show as green in WebStorm and in CI pipeline.

test.feature
```feature
Feature: Test feature
  Scenario: Test Scenario
    Given test given
    When test when
    Then test then
```

test.steps.ts
```ts
Before(() => {
  console.log('on before');
});

Given(/^test given$/, () => {
  expect(false).to.be.true; // THIS SHOULD FAIL 🚨
});
When(/^test when$/, () => {
  expect(true).to.be.true;
});
Then(/^test then$/, () => {
  expect(true).to.be.true;
});
```

Cucumber's `test_case_runner.js` emits hook results by firing a `test-step-finished` event:
```js
this.emit('test-step-finished', {
    index: this.testStepIndex, // 0
    result: testStepResult // { duration: 100500, status: "passed" }
});
```
Then a listener in `resultsCapturer` uses `testStepFinished` function to handle the result, but using 0 index it takes first step from the scenario steps and marks it as "passed" before it even started.

```js
function testStepFinished(data) {
  let feature = findFeature(data.testCase.sourceLocation);
  let scenario = findScenario(data.testCase.sourceLocation);
  let step = scenario.steps[data.index];
...
}
```

`findScenario` returns steps without hooks, which leads to a wrong step be resolved as "passed" (it takes the result of a Before hook)

![Screen Shot 2019-12-06 at 4 08 28 PM](https://user-images.githubusercontent.com/17122466/70328847-b44bdc00-1842-11ea-9c24-e7adef1f9255.png)

**Comment by Kungfoowiz** [comment]
We have this issue as well. XRay Jira plugin picks up Before and After results which are Passed.

But the actual Steps (Given, When, Then) have failed.

Is it possible to exclude these steps from the report and not report them?
