### ISSUE TITLE
How to get cucumberOpts in onPrepare?

### ISSUE THREAD

**Issue by nithingoudp** [protractor-cucumber-framework/protractor-cucumber-framework#180]
Similar to browser.getCapabilities() is there a way to read/get cucumberOpts in onPreapre?

**Comment by nehbehl** [comment]
An example syntax to achieve it as below:
 cucumberOpts: {
        // require step definitions
        tags: "@configFile",
        format: 'json:./reports/report.json',

        require: [
            './src/test/stepDefinitions/*.js'
        ]
    },
    onPrepare: () => {
        let bp = new BasePage();
}
};

**Comment by jan-molak** [comment]
@nithingoudp - what's the problem you're trying to solve?

**Comment by jan-molak** [comment]
Closing the issue since there's been no response from the OP.
