### ISSUE TITLE
Question: Do you know when v6.2.1 will be released?

### ISSUE THREAD

**Issue by beaucfr** [protractor-cucumber-framework/protractor-cucumber-framework#182]
Any update on when v6.2.1 will be published as mentioned in this thread:
https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/pull/178

**Comment by beaucfr** [comment]
Really looking forward to it! Thanks!

**Comment by rhucikfr** [comment]
@AlexandrosD any update please?

**Comment by AlexandrosD** [comment]
I will try to get this done in the weekend. No time guys, sorry about
that.. Please be patient

**Comment by Phonesis** [comment]
Many thanks @AlexandrosD 

It really is a major problem, causing huge issues with pipelines. So the sooner the better

**Comment by rhucikfr** [comment]
@AlexandrosD are you going to be able to provide 6.2.1?  If not, it's obviously a very simple process to create a release  for this project so can another maintainer/contributor create it instead of waiting for you?

**Comment by AlexandrosD** [comment]
@rhucikfr sorry but i cannot understand what you are saying..

**Comment by rhucikfr** [comment]
@AlexandrosD I asked if you're going to provide everyone with release v6.2.1 that has the retry logic fix commit that isn't part of v6.2.0.  You said you would try to get to it this weekend and I haven't seen a release.  So I was asking the status.  Not sure why you closed this issue as it hasn't been addressed.

**Comment by AlexandrosD** [comment]
@rhucikfr first, This is a question, not an issue. I am not gonna keep questions open indefinitely. That is why I closed it.

**Comment by AlexandrosD** [comment]
btw, v6.2.1 has been just published. But guys, this discussion really makes me think that I should stick with predefined release schedules, as the "on demand" thing clearly doesn't work. I know I said that I will "try" to publish it this weekend, but my time is limited. I can't just be there and release whatever gets merged. 

When you submit a PR, that gets merged, it should normally end up in the next planned release. This way we will avoid all the unnecessary discussion about when it will be released.

Also, this open source software. Meaning that if you want to use a feature that has been merged and not released/published in npm just yet, you can very well build it at your end and use it, especially if it's critical to you.
