### ISSUE TITLE
Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by ufm-uk** [protractor-cucumber-framework/protractor-cucumber-framework#183]
When attempting to fill a datatable in the feature file in the example below, the error _Cannot read property 'find' of undefined_. 

It may be an unsupported syntax as this example is from a Java feature file, is this syntax supported?

 Scenario Outline: <testCase> <expectedResult>

        Given user wants to create an employee with the following attributes
            | id  | firstName   | lastName   | dateOfBirth   | startDate   | employmentType   | email   |
            | 110 | <firstName> | <lastName> | <dateOfBirth> | <startDate> | <employmentType> | <email> |

        When user saves the new employee '<testCase>'
        Then the save '<expectedResult>'

        Examples:
            | testCase                 | expectedResult | firstName | lastName | dateOfBirth | startDate  | employmentType | email               |
            | WITHOUT FIRST NAME       | FAILS          |           | Green    | 1990-01-01  | 2018-01-01 | Permanent      | rachel.green@fs.com |
            | WITHOUT LAST NAME        | FAILS          | Rachel    |          | 1990-01-01  | 2018-01-01 | Permanent      | rachel.green@fs.com |
            | WITHOUT DATE OF BIRTH    | FAILS          | Rachel    | Green    |             | 2018-01-01 | Permanent      | rachel.green@fs.com |
            | WITHOUT START DATE       | FAILS          | Rachel    | Green    | 1990-01-01  |            | Permanent      | rachel.green@fs.com |
            | WITHOUT EMPLOYMENT TYPE  | FAILS          | Rachel    | Green    | 1990-01-01  | 2018-01-01 |                | rachel.green@fs.com |
            | WITHOUT EMAIL            | FAILS          | Rachel    | Green    | 1990-01-01  | 2018-01-01 | Permanent      |                     |
            | WITH ALL REQUIRED FIELDS | IS SUCCESSFUL  | Rachel    | Green    | 1990-01-01  | 2018-01-01 | Permanent      | rachel.green@fs.com |

**Comment by AlexandrosD** [comment]
Why do you think this is related to this project?

**Comment by ufm-uk** [comment]
It’s falling over inside you me library resultsCapturer.js:98 when this syntax is used. 

Kind regards 

Lee Carter
