### ISSUE TITLE
Process fails when there are ambiguous steps

### ISSUE THREAD

**Issue by rohitpratapitm** [protractor-cucumber-framework/protractor-cucumber-framework#185]
If there is any ambiguous step, the process fails with below error:
  √ Given I am on the "sei-highcharts-chart" demo page
  × And I expand the Demo Parameters and Outputs

**C:\src\common-highcharts-lib-ux\node_modules\protractor-cucumber-framework\lib\resultsCapturer.js:240**
                errorMsg: exception.message,
                                    ^
TypeError: ..\..\..\..\protractor-cucumber-framework\lib\resultsCapturer.js:52 Cannot read property 'message'
of undefined
    at commonStepFinished (C:\src\common-highcharts-lib-ux\node_modules\protractor-cucumber-framework\lib\resultsCapturer.js:240:37)
    at stepResultHandler (C:\src\common-highcharts-lib-ux\node_modules\protractor-cucumber-framework\lib\resultsCapturer.js:210:5)
    at ZoneDelegate.invokeTask (C:\src\common-highcharts-lib-ux\node_modules\zone.js\dist\zone-node.js:423:31)    at Zone.runTask (C:\src\common-highcharts-lib-ux\node_modules\zone.js\dist\zone-node.js:195:47)
    at ZoneTask.invokeTask (C:\src\common-highcharts-lib-ux\node_modules\zone.js\dist\zone-node.js:498:34)
    at ZoneTask.invoke (C:\src\common-highcharts-lib-ux\node_modules\zone.js\dist\zone-node.js:487:48)
[16:01:12] E/launcher - Process exited with error code
1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! common-highcharts-lib-ux@8.0.0-SNAPSHOT e2e: `cd node_modules/@sei/common-dev-tooling-lib-ux/tools/e2e && node test -e q02Mock -r -mock -conf`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the common-highcharts-lib-ux@8.0.0-SNAPSHOT e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rsikarwar\AppData\Roaming\npm-cache\_logs\2020-04-10T20_01_12_327Z-debug.log

****

After analysing I found out that [this piece of code](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/blob/57de19bcbbe5d8904867cba7c8acc11dd4138e6a/lib/resultsCapturer.js#L248) doesn't check for undefined.

After adding checks in resultCapturer.js code, it is working fine->
`
  case Cucumber.Status.AMBIGUOUS:
            emitterEvent = 'testFail';
            scenarioFailed = true;
            stepResults.assertions.push({
                passed: false,
                errorMsg: exception ? exception.message : 'Ambiguous step found.',
                stackTrace: exception ? exception.stack : undefined
            });
            break;
        case Cucumber.Status.FAILED:
            emitterEvent = 'testFail';
            scenarioFailed = true;
            stepResults.assertions.push({
                passed: false,
                errorMsg: exception ? exception.message : 'No Exception message found',
                stackTrace: exception ? exception.stack : undefined
            });
            break;

`

**Comment by rohitpratapitm** [comment]
Create PR for the same -> [here.](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/pull/186)

**Comment by jan-molak** [comment]
Serenity/JS supports [reporting ambiguous steps](https://github.com/serenity-js/serenity-js/blob/master/packages/cucumber/spec/listeners/messages/ambiguous_steps.spec.ts), so #198 will address this issue.

**Comment by jan-molak** [comment]
Serenity/JS has replaced the original implementation of `protractor-cucumber-framework` in `v8.0.0`, so this issue is now addressed. Please feel free to open a new ticket if you spot anything else, @rohitpratapitm!
