### ISSUE TITLE
JSON results not returned if job unexpectedly crashes

### ISSUE THREAD

**Issue by angfod** [protractor-cucumber-framework/protractor-cucumber-framework#195]
json results (cucumberOpts:{format:json}) only write at the end of the job, not after each scenario. As such, if a job unexpectedly crashes midway, you lose all results to that point, as the json file remains blank.

Is there a way to capture the results iteratively (after each scenario completion)? Or can that be added into the next patch release?

**Comment by yopasa94** [comment]
@angfod, I think you are missing   `ignoreUncaughtExceptions` parameter in the config file. I had a similiar issue running test in parallel and It was fixed adding that parameter

ignoreUncaughtExceptions: true

**Comment by jan-molak** [comment]
Since version `8.0.0` `protractor-cucumber-framework` uses [Serenity/JS](https://serenity-js.org) under the hood, which generates `json` reports after each scenario. See [Serenity/JS reporting](https://serenity-js.org/handbook/reporting/index.html).
