### ISSUE TITLE
Peer deependency still warns a need for cucumber

### ISSUE THREAD

**Issue by mrsegen** [protractor-cucumber-framework/protractor-cucumber-framework#196]
First, thank you @beradrian, @flaviencathala and other who contributed to the recent switch to 7.0.0.

A small issue is that we see this warning when running npm install for a project utilizing this package (and already switched to @cucmber/cucumber).
```
npm WARN protractor-cucumber-framework@7.0.0 requires a peer of cucumber@>= 1.3.0 but none is installed. You must install peer dependencies yourself.
```

It _may_ be as simple as changing [this line](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/blob/master/package.json#L65) to @cucumber/cucumber. But how do we choose the right minimum version of @cucumber/cucumber?

**Comment by flaviencathala** [comment]
It is a very valid concern especially with NPM 7 coming.
I have released 7.0.1 with @cucumber/cucumber as a peer dependency.
Thank you for catching it.
