### ISSUE TITLE
resultsCapturer.js fails when a gherkin Rule is being used

### ISSUE THREAD

**Issue by dahst** [protractor-cucumber-framework/protractor-cucumber-framework#199]
This part of the resultsCapturer fails when a Rule is being used in the feature being executed.
```
const featureChild =
  step && feature
    ? feature.children.find(c =>
        (c.scenario || c.background).steps.find(s => s.id === stepNodeId)
      )
    : undefined;
```
Error: TypeError: Cannot read property 'steps' of null

I _think_ Rule is meant to be supported: https://cucumber.io/docs/gherkin/reference/#rule

It breaks with or without a Background step within the Rule. 

The below seems to fix it, apologies but I don't have time to neaten it up/create a PR right now, might have time to come back to this later on.

```
const featureChild =
  step && feature
    ? feature.children.find(c =>
        c.rule ? c.rule.children.find(cr => (rc.scenario || rc.background).steps.find(s => s.id === stepNodeId)) :
        (c.scenario || c.background).steps.find(s => s.id === stepNodeId)
      )
    : undefined;
```

**Comment by flaviencathala** [comment]
@dahst 8.0.0 has been released and it might fix this issue. Can you please confirm? Thank you!

**Comment by dahst** [comment]
@flaviencathala 8.0.0 seems to have fixed it, great stuff!
For full disclosure: I'm having issues with require paths after the update so tested it with hardcoded full paths. Will close this issue.
