### ISSUE TITLE
Error trying to install v8

### ISSUE THREAD

**Issue by anselmbradford** [protractor-cucumber-framework/protractor-cucumber-framework#200]
I get this error when trying to yarn add the latest version:
```
error protractor-cucumber-framework@8.0.0: The engine "node" is incompatible with this module. Expected version "^10 || ^12 || ^14". Got "15.6.0"
error Found incompatible module.
```
Does `|| ^15` need to be added, or is it truly incompatible with 15?

**Comment by jan-molak** [comment]
Hey @anselmbradford! `protractor-cucumber-framework`, as well as [Serenity/JS](https://serenity-js.org), which it uses as its reporting engine, [have been tested](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/blob/master/.github/workflows/build.yml#L10) against the 3 most recent [Long-Term Support](https://nodejs.org/en/about/releases/) versions of Node.js, so 10, 12, and 14.

Version 15, just like any other odd-numbered Node.js release, is not on the LTS line and should be considered experimental.

I'd strongly recommend avoiding odd-numbered Node.js versions for production code and going with the latest LTS release instead.

Does this help?

**Comment by anselmbradford** [comment]
Thanks @jan-molak ! Makes sense. I'll close this.
