### ISSUE TITLE
Steps are not working with cucumberOpts

### ISSUE THREAD

**Issue by code4muktesh** [protractor-cucumber-framework/protractor-cucumber-framework#215]
Throwing error 
**Undefined. Implement with the following snippet**

Route cause:
if passing the cucumberOpts as
```
cucumberOpts: {
   require: [path.resolve('./tests/step_definitions/**/*.js')]
}
```
path.resolve is returning a path as c://tests//step_definitions

Notice, It is returning double slash "//" due to this, fast-glob.sync() inside @serenity-js is getting fail and nothing to pass --require cucumber so throwing error
**Undefined. Implement with the following snippet**

Please share the solution

**Comment by jan-molak** [comment]
Hi @code4muktesh,

While Serenity/JS understands glob patterns, `path.resolve` does not.
What you actually need is the following:

```
cucumberOpts: {
    require: [
        path.resolve('./tests/step_definitions') + '/**/*.js'
    ]
}
```

Hope this helps!
Jan
