### ISSUE TITLE
Unable to run failed tests

### ISSUE THREAD

**Issue by rudrathkr** [protractor-cucumber-framework/protractor-cucumber-framework#219]
Hi,

I am able to generate the rerun.txt file with the feature file that is failing. But unable to run it. 

created a config.ts file but how can i pass the rerun.txt to this ts file so that it runs only that feature file. Is there any cucumberopts command to do it .

Thanks,

**Comment by Gump0422** [comment]
Hi,
I got the same issue because "--rerun" CL has been removed in cucumber js 7.x, we can not using as follows now

`   cucumberOpts: {
      rerun: '@rerun.txt'
    }
    `
 Is there any other solution to fix it
 
 Thanks
