### ISSUE TITLE
Protractor being deprecated

### ISSUE THREAD

**Issue by Viktor-Bredihin** [protractor-cucumber-framework/protractor-cucumber-framework#232]
Any plans/advices regarding this news?

https://applitools.com/blog/migrating-protractor-tests-angular/

**Comment by jan-molak** [comment]
Hi @Viktor-Bredihin - `protractor-cucumber-framework` is powered by [Serenity/JS](https://serenity-js.org), so my suggestion for test suites using Protractor is to adopt [Serenity/JS Screenplay Pattern](https://serenity-js.org/handbook/design/screenplay-pattern.html) before Protractor gets deprecated. The difference between adopting Screenplay and simply re-writing your tests to use Cypress/Playwright/WebriverIO etc is that it will allow you to abstract your tests away from the underlying integration library (i.e. Protractor).

To get a feel of what's involved please see my [TodoMVC demo](https://github.com/serenity-js/todomvc-demo/tree/master/spec) for comparison of Protractor test script, Page Object-based implementation, and Screenplay Pattern-based implementation.

If you have any questions about the approach, please feel free to join our [Serenity/JS Community Chat on Gitter](https://gitter.im/serenity-js/Lobby)
