### ISSUE TITLE
Warning about incorrect engine with `npm 8`

### ISSUE THREAD

**Issue by tsimbalar** [protractor-cucumber-framework/protractor-cucumber-framework#237]
When used on Node v16 (LTS) , which comes with `npm v8`, we get those warnings : 

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'protractor-cucumber-framework@8.2.9',
npm WARN EBADENGINE   required: { node: '^12 || ^14 || ^16', npm: '^6 || ^7' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.1.0' }
npm WARN EBADENGINE }
```

Shouldn't this project allow usage of `npm v8` ? or maybe just drop the constraint about `npm` completely ? (and keep it only for `node`).

My understanding is that this needs to be updated in 

https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/blob/4996e3ae17018fd496aeab63f702ce75921ef640/package.json#L6-L9

thanks !

**Comment by jan-molak** [comment]
Good point, thanks for raising it
