### ISSUE TITLE
Playwright support 

### ISSUE THREAD

**Issue by isherkhan** [protractor-cucumber-framework/protractor-cucumber-framework#244]
HI

Are there any plans to build a similar package to support playwright-cucumber?

some thing like playwright-Cucumber-framework.(passing cucumber arguments through playwright runner)

thanks

**Comment by jan-molak** [comment]
Hi @isherkhan - yes, please follow this pull request in the main Serenity/JS repo - https://github.com/serenity-js/serenity-js/pull/911
