### ISSUE TITLE
Warning about incorrect engine with npm 9

### ISSUE THREAD

**Issue by tomiadebanjo** [protractor-cucumber-framework/protractor-cucumber-framework#268]
When used on Node v18 (LTS) , which comes with npm v9, we get those warnings :

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'protractor-cucumber-framework@8.2.9',
npm WARN EBADENGINE   required: { node: '^14 || ^16 || ^18', npm: '^6 || ^7' || ^8 },
npm WARN EBADENGINE   current: { node: 'v18.15.0', npm: '9.5.0' }
npm WARN EBADENGINE }

**Comment by tomiadebanjo** [comment]
Similar to the npm 8 issue resolved here - https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/issues/237

**Comment by jan-molak** [comment]
Thanks @tomiadebanjo! The requirement on the specific version of npm is not really necessary. I'll remove that in the next version.

**Comment by jan-molak** [comment]
Thanks for reporting the issue, @tomiadebanjo! Fixed in 9.3.0
