### ISSUE TITLE
Add support for cucumberjs v1.1.0 registerHandler api

### ISSUE THREAD

**Issue by tabanliviu** [protractor-cucumber-framework/protractor-cucumber-framework#38]
https://github.com/cucumber/cucumber-js/commit/7d7ba96262031b4fb7ab83216f474817d3892f3f
has changed the way registerHandler is implemented by deprecating getPayloadItem

see https://github.com/cucumber/cucumber-js/blob/7d7ba96262031b4fb7ab83216f474817d3892f3f/lib/cucumber/runtime/event.js#L14

**EDIT**: Actually the break is from the use of of callback and returning a promise.
But since that was the error displayed I assumed it was the cause
~~(_Currently it breaks when used with cucumberjs 1.1.0 and protractor 2.3.0_)~~

**Comment by mattfritz** [comment]
Is it broken or just showing the deprication message? @eis95 opened https://github.com/mattfritz/protractor-cucumber-framework/pull/40 for this a few days ago, but I have not integrated it yet

**Comment by eis95** [comment]
AFAIK it was just showing the deprecation message. OP may have seen different results.

**Comment by tabanliviu** [comment]
@mattfritz Updated the ticket. It was a combination of warning + unrelated error (callbacks + promises at the same time from 1.1.0) that didn't have an error output that made it seem like this was a breaking change

**Comment by eis95** [comment]
Any reason the pull request hasn't been brought in?

**Comment by aluzardo** [comment]
Maybe this issue also could be fixed with @eis95 pull request.

https://github.com/mattfritz/protractor-cucumber-framework/issues/55

**Comment by darrinholst** [comment]
this has been incorporated in v1.0.0
