### ISSUE TITLE
Running 'npm start' not working on Windows10 using gitbash

### ISSUE THREAD

**Issue by eis95** [protractor-cucumber-framework/protractor-cucumber-framework#44]
Just running `npm start` I get the following message: 
`Starting HTTPster v1.0.3 on port "'process.env.HTTP_PORT" from testapp/`

It seems like this should default to the webServerDefaultPort in environment.js.

I can get the app running by changing the start script in package.json to
`"start": "httpster -d testapp/ -p 8081",`

**Comment by mattfritz** [comment]
The `npm start` script is hardcoded for UNIX systems right now, which is probably why the backticks are not executing properly.

I don't have a Windows system to test on, but if you can confirm an approach that works for both OS' I can make the change. Let me know.

**Comment by eis95** [comment]
I'll look at providing that.
