### ISSUE TITLE
Running 'npm test' not working on Windows10 using gitbash

### ISSUE THREAD

**Issue by eis95** [protractor-cucumber-framework/protractor-cucumber-framework#45]
When running `npm test` I get the following output. 

`

> protractor-cucumber-framework@0.6.0 test .\protractor-cucumber-framework
> node test.js

running: node_modules/protractor/bin/protractor spec/cucumberConf.js

> > > fail: Error: spawn node_modules/protractor/bin/protractor ENOENT
> > > running: node_modules/protractor/bin/protractor spec/cucumberConf.js --cucumberOpts.tags @failing
> > > fail: Error: spawn node_modules/protractor/bin/protractor ENOENT
> > > running: node_modules/protractor/bin/protractor spec/cucumberConf.js --cucumberOpts.tags @failing --cucumberOp                           ts.fail-fast
> > > fail: Error: spawn node_modules/protractor/bin/protractor ENOENT
> > > running: node_modules/protractor/bin/protractor spec/cucumberConf.js --cucumberOpts.tags @strict --cucumberOpt                           s.strict
> > > fail: Error: spawn node_modules/protractor/bin/protractor ENOENT
> > > running: node_modules/protractor/bin/protractor spec/cucumberConf.js --cucumberOpts.tags @strict
> > > fail: Error: spawn node_modules/protractor/bin/protractor ENOENT
> > > running: node_modules/protractor/bin/protractor spec/multiConf.js --cucumberOpts.tags @failing
> > > fail: Error: spawn node_modules/protractor/bin/protractor ENOENT
> > > Summary: fail
> > > npm ERR! Test failed.  See above for more details.
> > > `

I can get all tests to pass by running `protractor spec/cucumberConf.js` and then `protractor spec/multiConf.js`

**Comment by mattfritz** [comment]
`ENOENT` means it can't find the executable it needs to spawn, and this test suite is hardcoded to spawn a specific binary. Can you provide info about what is in that directory on you machine?

I expect strange behavior from Windows `gitbash`... Let me know what you find

**Comment by eis95** [comment]
### running via npm test

$ npm test

> protractor-cucumber-framework@0.6.0 test F:\repos\OpenSource\protractor-cucumber-framework
> node test.js

running: protractor spec/cucumberConf.js
>>> fail: Error: spawn protractor ENOENT
running: node_modules/protractor/bin/protractor spec/cucumberConf.js --cucumberOpts.tags @failing
>>> fail: Error: spawn node_modules/protractor/bin/protractor ENOENT
running: node_modules/protractor/bin/protractor spec/cucumberConf.js --cucumberOpts.tags @failing --cucumberOpts.fail-fast
>>> fail: Error: spawn node_modules/protractor/bin/protractor ENOENT
running: node_modules/protractor/bin/protractor spec/cucumberConf.js --cucumberOpts.tags @strict --cucumberOpts.strict
>>> fail: Error: spawn node_modules/protractor/bin/protractor ENOENT
running: node_modules/protractor/bin/protractor spec/cucumberConf.js --cucumberOpts.tags @strict
>>> fail: Error: spawn node_modules/protractor/bin/protractor ENOENT
running: node_modules/protractor/bin/protractor spec/multiConf.js --cucumberOpts.tags @failing
>>> fail: Error: spawn node_modules/protractor/bin/protractor ENOENT
Summary: fail
npm ERR! Test failed.  See above for more details.


### running the last test manually
$ node_modules/protractor/bin/protractor spec/multiConf.js --cucumberOpts.tags @failing
[13:13:41] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[13:13:41] I/launcher - Running 1 instances of WebDriver
Feature: Running Cucumber with Protractor

    As a user of Protractor
    I should be able to use Cucumber
    to run my E2E tests

  @dev
  Scenario: Running Cucumber with Protractor
    Given I run Cucumber with Protractor
    Then it should still do normal tests
    Then it should expose the correct global variables

  @dev
  Scenario: Wrapping WebDriver
    Given I go on "index.html"
    Then the title should equal "My AngularJS App"

2 scenarios (2 passed)
5 steps (5 passed)
0m00.381s
[13:13:46] I/launcher - 0 instance(s) of WebDriver still running
[13:13:46] I/launcher - chromeANY #01 passed


FYI: I am running npm 3.8.7 and node 4.4.3

**Comment by eis95** [comment]
To better answer your question:
$ ls -la
total 25
drwxr-xr-x 1 ed 197121     0 Jul 14 09:39 .
drwxr-xr-x 1 ed 197121     0 Jul 21 07:45 ..
-rwxr-xr-x 1 ed 197121  1283 Jul 14 09:39 elementexplorer.js
-rwxr-xr-x 1 ed 197121   105 Jul 14 09:39 protractor
-rwxr-xr-x 1 ed 197121 15210 Jul 14 09:39 webdriver-manager

**Comment by mattbrunetti** [comment]
I figured out the problem, sortof. On Windows `child_process.spawn()` does not seem to detect files that have no filename extension. Not sure why, but it doesn't really matter since on Windows we should be targetting `protractor.cmd`. It's not in `node_modules/protractor/bin` but it gets installed to `node_modules/.bin`.

PR coming
