### ISSUE TITLE
Supporting multicapabilities with consolidated cucumber JSON

### ISSUE THREAD

**Issue by thyagab** [protractor-cucumber-framework/protractor-cucumber-framework#46]
Currently there is no consolidated JSON available if we have multicapabilities. There is 1 current pull request pending to generate the individual json files.
https://github.com/mattfritz/protractor-cucumber-framework/pull/25/commits/578a4660f02a3e1b2587053ded57b547f97e26ef

If we can have a consolidated JSON file, it would be easy to generate overall test execution report otherwise we need to keep having individual files.

**Comment by mattfritz** [comment]
I think this is a good idea... Let me take a look this week

**Comment by thyagab** [comment]
@mattfritz Thank you for considering. generating individual json files could only be a stop gap fix. If we could generate a consolidated JSON that would be ideal.

**Comment by thyagab** [comment]
@mattfritz currently there is a consolidated Json generated with minimum details when multi capabilities is enabled.  This is generated when we provide resultjsinoutput in protractor config. If we can generate cucumber generated json that would solve the issue.

**Comment by wyvern8** [comment]
Thanks for looking into this one.  I am current using the above pull request for individual files, with a separate base json path in cucumberOpts/format for each capability, and then a grunt task to join each webdriver json for each capability so that we can generate reports per browser.  It works, but if this can be done as part of this module it would great!

**Comment by thyagab** [comment]
@mattfritz Any update on this enhancement?

**Comment by thyagab** [comment]
@wyvern8 if you are using the above pull request, you can use cucumber html reporter("cucumber-html-reporter": "~0.2.8",) for consolidated report. Kush had implemented a new feature request to support multiple files and it works fine.

**Comment by wyvern8** [comment]
@thyagab thanks, will take a look.  At the moment I'm joining the sharded json output myself for each device and using this, https://www.npmjs.com/package/grunt-protractor-cucumber-html-report but the one you reference looks great.

**Comment by Joel-fogue** [comment]
This feature would be very helpful for us as well; as we use a cucumber plugin in our Bamboo pipeline. And that cucumber plugin only expects a single JSON as input in order to generate the visual report. For now, I'm thinking I can use a gulp task to consolidate manually but this enhancement would be ideal.

**Comment by thyagab** [comment]
@mattfritz any update on this feature?

**Comment by pittgoose** [comment]
Any update on this? Is someone working on it? @mattfritz? I could really use this feature.

**Comment by darrinholst** [comment]
As of v2.1.0 we will add the PID to any formatters with a path if you're sharding or using multi-capabilities. This results in a file for every process that protractor spawns. 

As far as I know (please correct me if I'm wrong) we don't have the ability to consolidate them into 1 file in this library. Protractor spawns whatever processes it needs and calls us to tell us to run certain specs/features. We don't know anything about any other processes.

My suggestion would be to use a separate library to do this consolidation after protractor is finished such as [cucumber-html-reporter](https://github.com/gkushang/cucumber-html-reporter#jsondir) referenced earlier or use a [gulp task](https://github.com/joshswan/gulp-merge-json).

**Comment by pradeep-kumar-JP** [comment]
I am trying parallel execution for angular application using protractor-cucumber-framework , i have tried with 2 types of capabilities but i am getting only last executed feature file json report , below are the 2 types of capabilities i have used.
1)
capabilities: {
browserName: 'chrome',
shardTestFiles: 'true',
maxInstances: 3,
},
2)
multiCapabilities: [
{
shardTestFiles: true,
browserName:'chrome',
},
{
shardTestFiles: true,
browserName: 'internet explorer',
}
],

my cucumber opts look like this:

cucumberOpts: {
require:[ 'Generic_Protractor/StepDefinitions//*.js', 'Generic_Protractor/Support//*.js' ],
format: [ 'json:Generic_Protractor/Report/cucumber_report.json', 'pretty' ],
plugin : "pretty",
keepAlive: false

}
Please help me out to get complete json report.

Thanks in advance

**Comment by darrinholst** [comment]
what versions of protractor, cucumber, and protractor-cucumber-framework are you using?

**Comment by pradeep-kumar-JP** [comment]
@darrinholst 
Protractor version - 4.0.10
cucumber version - 1.3.1
protractor-cucumber-framework -0.6.0

**Comment by pradeep-kumar-JP** [comment]
@darrinholst 
When i used Protractor and cucumber of latest version,
Protractor version - 5.1.1
cucumber version - [1.3.2]
protractor-cucumber-framework -0.6.0

I am getting incomplete and invalid report and i am attaching it in .txt form 
 
[cucumber_report.txt](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/files/927590/cucumber_report.txt)

**Comment by darrinholst** [comment]
The work done for this issue wasn't released until v2.1.0. You'll  need to upgrade to at least that to start getting log files per process. https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/issues/46#issuecomment-292232336

**Comment by pradeep-kumar-JP** [comment]
@darrinholst 
I am sorry but can you tell me version of what should be upgraded?

**Comment by darrinholst** [comment]
protractor-cucumber-framework

**Comment by pradeep-kumar-JP** [comment]
@darrinholst 
Thanks darrinholst , 
After updating  protractor-cucumber-framework its generating separate json file , do we have any existing node module utility to generate consolidated json?

**Comment by darrinholst** [comment]
Please see my comments earlier in this issue.

**Comment by pradeep-kumar-JP** [comment]
@darrinholst 
Thank you so much for your help

**Comment by edgarechm** [comment]
Excuse me, but I got lost where the solution to have a single consolidated cucumber.json was found.

I ran 5 instances with shardfiles on 5 features, all I get is 5 separated json files. Not a consolidated.

Are there any updates on this?

**Comment by darrinholst** [comment]
A separate file for each process is the expected behavior. There’s nothing we can do here to consolidate them. You’ll need to use a post processing step to do that or use a report generator that can take multiple files as input. See [previous comment](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/issues/46#issuecomment-292232336)

**Comment by BimalPatra** [comment]
'use strict';

exports.config = {

directConnect: true,
//  getPageTimeout = 60000,

multiCapabilities: [
    {
      browserName: 'chrome',
      'chromeOptions': {
        'args': ['disable-infobars']
      },
      maxInstances: 2,
      specs: ['./test/e2e/features/AddDevice1.feature'],
    },
    {
      browserName: 'firefox',
      'moz:firefoxOptions': {
        'args': ['--safe-mode']
      },
      maxInstances: 2,
      specs: ['./test/e2e/features/AddDevice2.feature'],
    }
 ], 

//set framework options
framework: 'custom',
frameworkPath: require.resolve('protractor-cucumber-framework'),

//just maximizing window before testing
onPrepare: function(){
    browser.waitForAngularEnabled(true);
    browser.driver.manage().window().maximize();
    browser.getCapabilities().then(function (cap) {
      browser.browserName = cap.caps_.browserName;
    });
 } ,

//Create html  report
onComplete: () => {
 //var reporter = require('cucumber-html-reporter');
 var reporter = require('protractor-multicapabilities-htmlreporter');
 var options = {
   theme: 'bootstrap',
   jsonFile: './*.json',
   output: './results.html',
   reportSuiteAsScenarios: true,
   launchReport: true,
   metadata: {
       "App Version":"0.3.2",
       "Test Environment": "STAGING",
       "Browser": "Chrome  54.0.2840.98",
       "Platform": "Windows 10",
       "Parallel": "Scenarios",
       "Executed": "Remote"
   },
   output: './test/e2e/report/cucumber_report.html',
 };
  reporter.generate(options);
  //exec("node ./test/e2e/Steps/Commn_Function/Email.js",puts);
},

//set cucumber options

cucumberOpts: {
     require: ['./test/e2e/Steps/*.js','./Commn-Function/chaiAssertions.js','./test/e2e/Steps/Commn-Function/hook.js'],
     strict: true,
     //format: [],    //don't put 'Pretty' as it is depreciated
     'dry-run': false,
     compiler: [],
     format: 'json:results.json',    //make sure you are not using multi-capabilities
     //tags: '@Smoke or @Smoke111'
     tags: '@Sanity'
   },
 SELENIUM_PROMISE_MANAGER: false,
 };

**Comment by BimalPatra** [comment]
Q1:can any body help me,it is creating multiple report json files and I could not able to generate report
Q2:How can I delete the created multiple josn files before running it again.

i am using multicapabilities.
