### ISSUE TITLE
shardTestFiles option starts webdrivers for features regardless of tag match

### ISSUE THREAD

**Issue by wyvern8** [protractor-cucumber-framework/protractor-cucumber-framework#51]
http://stackoverflow.com/questions/38516527/protractor-shardtestfiles-with-cucumberopt-tags-starts-unnecessary-webdrivers

Anyone have any thoughts on this one?

**Comment by thyagab** [comment]
Any update on this issue? has some one worked on this? implemented?

**Comment by dirkluijk** [comment]
👍 +1

**Comment by darrinholst** [comment]
I'm not sure how you would do this in this library. We get the list of specs/features to execute here before any tag or name filtering is applied by cucumber. You'd need to construct your list of features/scenarios to pass in to protractor that is cucumber aware like mentioned [here](http://stackoverflow.com/questions/38516527/protractor-shardtestfiles-with-cucumberopt-tags-starts-unnecessary-webdrivers#comment64543586_38516527). I've done my own sharding like shown [here](https://gist.github.com/darrinholst/bd00aa0f40d5978a84c47b012215b080), but again, this is at the protractor conf building stage.

I'd be for putting some scenario list generator utilities in here that we could use in our protractor conf so we wouldn't have to paste code like that from project to project.
