### ISSUE TITLE
Good to have ability to list all step definitions

### ISSUE THREAD

**Issue by jeffreyguo** [protractor-cucumber-framework/protractor-cucumber-framework#53]
Good to know what steps already exist and know which files they are sitting in.

**Comment by darrinholst** [comment]
Not sure what version this was put in, but cucumberjs has a `usage` formatter that you can use - https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#formats

**Comment by darrinholst** [comment]
it was just put in to 2.0.0-rc.6 (2017-01-06)
