### ISSUE TITLE
Running multiple scenarios in 1 feature file 

### ISSUE THREAD

**Issue by nachchid** [protractor-cucumber-framework/protractor-cucumber-framework#58]
I am using protractor-cucumber-framework version 0.6.0.   I am having the same problem with multiple scenarios. 

https://github.com/mattfritz/protractor-cucumber-framework/issues/26

Is this issue fixed? 

Also having sleep in protractor page object model. Cucumber test fail with a time out.  Without the sleep the test are passing.  Is this related ?

**Comment by darrinholst** [comment]
I run many scenarios in a feature file without any problems. If you can provide a sample app that demonstrates the problem I'd be happy to take a look at it.
