### ISSUE TITLE
Synchronise cucumber steps with protractor control flow

### ISSUE THREAD

**Issue by AlexandrosD** [protractor-cucumber-framework/protractor-cucumber-framework#60]
Currently cucumber's steps are not synched with protractor control flow.
This is the root cause of the following issues:
- https://github.com/domenic/chai-as-promised/issues/160
- https://github.com/timjroberts/cucumber-js-tsflow/issues/4
- https://github.com/mattfritz/protractor-cucumber-framework/issues/56

An adapter similar to the one protractor has for jasmine is needed for cucumber as well, as @Jan points out in https://github.com/domenic/chai-as-promised/issues/160#issuecomment-246327610

**Comment by AlexandrosD** [comment]
A PR is being prepared for this and will be submitted shortly.

**Comment by jlin412** [comment]
+1  Any update on that?
