### ISSUE TITLE
Expose duration information in protractor events 

### ISSUE THREAD

**Issue by segrey** [protractor-cucumber-framework/protractor-cucumber-framework#62]
It'd be great to add information about scenario execution duration in event object passed to protractor runner (https://github.com/mattfritz/protractor-cucumber-framework/blob/v0.6.0/lib/resultsCapturer.js#L41).
It would allow other tools (e.g. IDE) to show this information. For instance, WebStorm 2016.3 supports Protractor runner and it could show scenario duration information in test result tree.

**Comment by jan-molak** [comment]
@segrey - Does the WebStorm Protractor plugin look for the `duration` property already, so adding it here will magically make everything work, or does the behaviour you have in mind need to be implemented in WebStorm first?

**Comment by segrey** [comment]
@jan-molak Not yet, only the next WebStorm 2017.1 EAP will look for `durationMillis` property on `scenarioInfo` object. Most likely this WebStorm build will be available this week. I'll let you know.

**Comment by jan-molak** [comment]
@segrey sounds great, thank you! I'll add this functionality to Serenity/JS and we can submit a PR here too if needed. [Serenity/JS #18](jan-molak/serenity-js/issues/18)
