### ISSUE TITLE
running specific scenarios from a feature file

### ISSUE THREAD

**Issue by Galileo1** [protractor-cucumber-framework/protractor-cucumber-framework#70]
Hey Guys, 

I am trying to run specific scenarios from a single feature file by providing expression like this - 'e2e-tests\\features\\**\\Feature Editor.feature:5'. Where ':5' is the line number of the scenario which i want to trigger. 

Could you please let me know if this is feasible if I am using - 
Protractor 4.0.11
Cucumberjs 1.3.1
protractor-cucumber-framework 0.6.0

**Comment by mattbrunetti** [comment]
@Galileo1 You should be able to do that, either by specifying line numbers or (the way I would prefer to do it) tags. Check out [this commit](https://github.com/cucumber/cucumber-js/commit/95c6f29cc4c85d02d042ed5b3f9ff270eee88b89) and maybe [this issue](https://github.com/cucumber/cucumber-js/issues/305)

**Comment by Galileo1** [comment]
@mattbrunetti I asked the same question on [cucumber-js repo](https://github.com/cucumber/cucumber-js/issues/728) but seems like they have different opinion. 

Since I m using protractor with cucumber as custom framework I can't use cucumberjs commands. I have to trigger the testcases using protractor.

Is there a way to handle this in this repo?

**Comment by mattbrunetti** [comment]
@Galileo1 I was able to target a specific scenario by providing a `"name"` under `"cucumberOpts"` in my `protractor.conf.js` file. At some point I'll edit that config file to get that value from the command-line arguments.

Good to know that Cucumber supports targeting individual scenarios by name. Even better than tags, for my purposes.

**Comment by Galileo1** [comment]
this is awesome I will give it a go.Thanks for prompt reply.

**Comment by Galileo1** [comment]
passing cucumberOpts.name=['name of scenario'] from command line to protractor config file works like  a charm. Thanks a ton.

**Comment by mattbrunetti** [comment]
Hmm.. yeah that would be pretty useful wouldn't it..

Seems like an issue for the cucumberjs repo though, since we can pass any options to cucumber through protractor-cucumber-framework. The problem is that cucumber's "name" option only supports one name, right? Or is it a matter of protractor not parsing a literal array in the command-line args?

**Comment by pawelus** [comment]
It is partially possible in Protractor 4.x.

You can pass ":line_number" but the path can't have any glob components so this will work:
```
./features/some_dir/feature_file.feature:5
```
but this won't:
```
./features/**/feature_file.feature:5
```

**Comment by Galileo1** [comment]
thanks @pawelus.

**Comment by Galileo1** [comment]
@mattbrunetti so far I am able to supply one name. multiple scenario doesn't work so far but [cucumberjs ](https://github.com/cucumber/cucumber-js/blob/master/src/cli/argv_parser.js)  suggests array ` .option('--name <REGEXP>', 'only execute the scenarios with name matching the expression (repeatable)', ArgvParser.collect, [])`. I m not sure protractor is causing it or not.

**Comment by darrinholst** [comment]
To summarize the available options...

* the `:[line number]` format only works for absolute file names, i.e. no glob patterns.
* tags could work which is what I usually use.
* wasn't aware of the name option, but that works too. From the command line you have to repeat the `--cucumberOpts.name` arg for each name in the multi scenario situation. You'd specify an array in `cucumberOpts` from the config file. Example for the cli is [here](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/blob/c07f7b941118848077e1cdca098462a1106e0854/test/test.js#L49).

Reopen if this is still an issue.

**Comment by Ankitdet** [comment]
@Darrin Holst, Can you provide an example for.

the :[line number] format only works for absolute file names, i.e. no glob patterns

**Comment by darrinholst** [comment]
@Ankitdet 

``` bash
protractor --capabilities.specs features/example.feature:2
```

**Comment by Ankitdet** [comment]
Thanks @darrinholst
