### ISSUE TITLE
MAINTAINER NEEDED

### ISSUE THREAD

**Issue by mattfritz** [protractor-cucumber-framework/protractor-cucumber-framework#73]
I no longer have the time to maintain this package and no longer use this day-to-day, so it makes sense to hand it off to someone with vested interest RE: https://github.com/mattfritz/protractor-cucumber-framework/issues/69

@darrinholst (or others) are you interested in maintaining? I see you have a fork. Let me know and I'll take care of it.

**Comment by csvan** [comment]
+1 for @darrinholst

**Comment by AlexandrosD** [comment]
Thanks for the heads up @mattfritz. It would be great if @darrinholst could take over, you can also take my support for granted, to the best possible extent. I also count on @jan for porting over his improvements that are now part of serenityjs.

**Comment by pittgoose** [comment]
I'd love to work on this. @darrinholst I'll hit you up directly on Gitter.

**Comment by darrinholst** [comment]
I set up a new org so we don't run into this problem again. I don't want to take full responsibility for it since projects like these tend to go in and out of maintainers radars depending on what other projects they're working on at the time. @AlexandrosD and @pittgoose I'll add you guys to the org and we can go from there.

**Comment by mattbrunetti** [comment]
@darrinholst We are starting to use this package at @ManitoulinTransport and we'd like to offer our support. You could add me to the org if you wish.

**Comment by mattfritz** [comment]
Looks like existing PRs and issues don't show up on the new org repo... I can transfer ownership to the org if that is desired vs. fragmenting history

**Comment by darrinholst** [comment]
Sure that'll work. I just used my fork since it already had support for cucumber 2 in. I'll merge it back once you transfer it.

**Comment by mattfritz** [comment]
Looks like orgs can only have one repo in the same network... 

![image](https://cloud.githubusercontent.com/assets/2037226/23475306/645b873a-fe74-11e6-93e4-93d9448f17ad.png)

Can you delete the fork or publish it as a non-networked repo?

**Comment by darrinholst** [comment]
done

**Comment by mattfritz** [comment]
Transfer is complete. Thank you all for your work and especially your patience

**Comment by darrinholst** [comment]
No problem and thanks for following up. The 10s of users of this appreciate
it ;)

**Comment by csvan** [comment]
@mattfritz thanks for all your work on this project. Best of luck on your endeavors, and hope to see you around :)

**Comment by darrinholst** [comment]
Reopening to withdraw from lead maintainer responsibilities from much the same reasons as Matt originally opened this for.

@AlexandrosD @mattbrunetti @pittgoose you all were added to the org when we first switched over and I have made you all owners. 

If there is anyone else interested in carrying on the torch here I would be happy to add you. 

We would still need to add some more people to the npm package as maintainers so they could do releases.

**Comment by AlexandrosD** [comment]
Sad to see you go. I'll 

I accept the ownership responsibilities and continue from where you left. I trust you guys are still around..

**Comment by darrinholst** [comment]
Thanks, @AlexandrosD. Do you have an npm account that I can add as a maintainer?

**Comment by AlexandrosD** [comment]
@darrinholst yes, it's alexandrosd

**Comment by pittgoose** [comment]
I would love to contribute at some point but at the moment I still find a lot of what's going on here to be over my head. I've been trying to familiarize myself with the code and I can probably do a review, but I'm not knowledgeable enough to take a lead role.

**Comment by AlexandrosD** [comment]
Reopening this, as now it's my turn to look for maintainers I guess.
I don't have the time right now, and it's been a while since last time I actually worked with protractor or angular.
I see there are a few PRs and a few issues open - is anyone willing to take the lead from here?

Thanks,
Alex

**Comment by beradrian** [comment]
It's a good tool, I'll hate to see it dying, so count me in.

**Comment by flaviencathala** [comment]
I can give a hand as well.

**Comment by jan-molak** [comment]
Hey team, as per https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/issues/191#issuecomment-762554803, Cucumber 7 uses has changed the format and contents of its internal events.

I've recently added support for Cucumber 7 to Serenity/JS, so it now supports all the Cucumber versions. `@serenity-js/protractor` module can now also act as a [drop-in replacement](https://serenity-js.org/handbook/integration/serenityjs-and-protractor.html#using-native-cucumber-reporters) of `protractor-cucumber-framework`. 

If any new maintainer of `protractor-cucumber-framework` would like to avoid the work needed to make this project support the latest version of Cucumber (and any future versions), I'd be happy to help you migrate the internals to use Serenity/JS Cucumber adapters under the hood.

**Comment by flaviencathala** [comment]
Thank you @jan-molak !
If you think Serenity/JS would fit well as a dependency of this project it might be a good long-term alternative.
In the meantime I have provided a fix for Cucumber 7 events compatibility (https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/pull/194).

**Comment by flaviencathala** [comment]
@AlexandrosD could you please give someone maintainer rights and/or merge https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/pull/194 please? My npm account is "flavien_cathala".

**Comment by flaviencathala** [comment]
@AlexandrosD could you please give someone maintainer rights and/or merge and publish #194 please? My npm account is "flavien_cathala".

**Comment by Zialus** [comment]
@AlexandrosD any updates?

**Comment by AlexandrosD** [comment]
Apologies for taking so long, but.. a lot's going on over here.
Anyways..

beradrian & @flaviencathala : I've just given you maintainer rights in the repo. @flaviencathala I've also added you as maintainer in npm.

Good luck, please keep this project alive. Also, I would consider @jan-molak 's suggestion - he has done an excellent work there.

**Comment by flaviencathala** [comment]
Thanks @AlexandrosD I have published protractor-cucumber-framework@7.0.0 with Cucumber 7 compatibility.
If I can add something to @jan-molak suggestion, Cucumber formatters may not work when migrating to @serenity-js. For instance if using the popular @cucumber/pretty-formatter it can be replaced by @serenity-js/console-reporter.

```javascript
const { ConsoleReporter } = require('@serenity-js/console-reporter');

		frameworkPath: require.resolve('@serenity-js/protractor/adapter'),
		serenity: {
			runner: 'cucumber',
			crew: [ConsoleReporter.withDefaultColourSupport()]
		}
```

**Comment by jan-molak** [comment]
Great work @flaviencathala!

You're right, that's because Cucumber seems to now support only [one formatter per output](https://github.com/cucumber/cucumber-js/blob/625fab034eea768bf74f7a46993a57182204ddf6/src/cli/index.ts#L90-L108), and `@serenity-js/cucumber` takes over the `stdout` output.

I wrote a fix for it yesterday and would like to do some more testing on Windows to make sure it's all working as expected.

I'll submit a PR for you to review soon.

Best,
Jan

**Comment by flaviencathala** [comment]
@AlexandrosD could you please give Admin rights to me and/or @jan-molak on this repo so we can change the settings? We would like to enable Renovate and automated package releases.

**Comment by AlexandrosD** [comment]
Done

Στις Πέμ, 25 Μαρ 2021 στις 8:52 π.μ., ο/η Flavien Cathala <
***@***.***> έγραψε:
