### ISSUE TITLE
[Question] Sharding reports?

### ISSUE THREAD

**Issue by NHKK** [protractor-cucumber-framework/protractor-cucumber-framework#78]
Does anyone know if the new version allows for creation of multiple json reports? because in the older version I see that only the last feature that runs gets recorded when I shard. I know there are hacky methods around this but would prefer that it's built in to the system.

**Comment by darrinholst** [comment]
No, not yet. There is pr #25 out there that needs conflicts resolved and there's issue #46 to consolidate them all in to 1 file.
