### ISSUE TITLE
How to Implement Serenity Report

### ISSUE THREAD

**Issue by vaishalisenthilkumar** [protractor-cucumber-framework/protractor-cucumber-framework#80]
Hi,

We are trying to implement Serenity Report for our Protractor Project with Javascript. 

Could you please help us out on this.

Thanks,

**Comment by mattbrunetti** [comment]
I'm not too familiar with the Serenity project, but I think you may want to check out the drop-in replacement for this package, [serenity-js](https://github.com/jan-molak/serenity-js) by @jan-molak

**Comment by darrinholst** [comment]
As well as serenity-js as @mattbrunetti mentioned you could check out [custom cucumber formatters](https://github.com/cucumber/cucumber-js/blob/master/docs/custom_formatters.md) if you need to do something custom. I don't think there's anything to do in this library.

**Comment by jan-molak** [comment]
@vaishalisenthilkumar - please check the tutorial at [serenity-js.org](http://serenity-js.org/from-scripts-to-serenity/readme.html)

@mattbrunetti, @darrinholst - thanks for the mention 👍
