### ISSUE TITLE
Provide source location information

### ISSUE THREAD

**Issue by segrey** [protractor-cucumber-framework/protractor-cucumber-framework#81]
Now protractor-cucumber-framework is emitting scenarios and steps in form
```javascript
{
    "category": "scenarios",
    "name": "step name"
}
```
That's great. One missing feature is navigation from the test tree to source code.
Unfortunately, IDE doesn't support navigation for scenarios/steps, but it can easily navigate to the provided location. E.g. extend it with `sourceLocation`:
```javascript
{
    "category": "my category",
    "name": "my name",
    "sourceLocation": {
        "filePath": "/path/to/file",
        "line": "<one based line number>"
        "column": "<one based column number>"
    }
}
```
Some related discussion https://github.com/jan-molak/serenity-js/issues/18

**Comment by darrinholst** [comment]
@segrey will this work in WebStorm 2017.1.1? I'm sending the following, but not getting any navigation...

``` js
{ 
  name: 'Given I am logged in',
  category: 'Add Case: ',
  durationMillis: 24,
  sourceLocation: { 
     filePath: '/Users/darrinholst/Projects/project/features/e2e/add-case.feature',
     line: 3,
     column: 1 
  } 
}
```

**Comment by segrey** [comment]
@darrinholst Nope, it won't work in WebStorm 2017.1.1. Sorry for being unclear. I meant if `testInfo` would be extended with this information somehow, e.g. in the above-mentioned way, IDE could use it. Thanks for adding this info so quickly! Look like it works great with protractor-cucumber-framework@3.1.0. Support on IDE side will be added in WebStorm 2017.1.3.
Meanwhile, you can try it out in WebStorm 2017.1.1 by replacing content of protractor-intellij-plugin.js file (which is located inside `helpers/protractor-intellij/lib` folder; to locate that folder, please inspect the command line that starts protractor tests in IDE) with content of [protractor-intellij-plugin.js.txt](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/files/923084/protractor-intellij-plugin.js.txt).

Regarding `sourceLocation`:
* `column` field can simply be omitted if not known
* looks like we need to extend `sourceLocation` a bit further to be able to navigate from scenario nodes too (currently, it doesn't navigate). For instance, maybe something like
```
{
    "category": "my category",
    "name": "my name",
    "sourceLocation": {
        "category": { filePath, line, column }
        "name": { filePath, line, column}
    }
}
```
What do you think?

**Comment by darrinholst** [comment]
Ok, makes sense. I'll let you guys hash out the sourceLocation changes over in https://github.com/jan-molak/serenity-js/issues/18 (says the vim guy ;)). Just open up another issue if changes are needed.
