### ISSUE TITLE
Receive errors when try to start the test app with $npm start

### ISSUE THREAD

**Issue by Syslog2905** [protractor-cucumber-framework/protractor-cucumber-framework#83]
Please take a look at this log:
g.ivanova@DESKTOP-1UCJ33I MINGW64 ~
$ npm start

> protractor-cucumber-framework@3.1.0 start C:\Users\g.ivanova
> node test/testapp/server

module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Users\g.ivanova\test\testapp\server'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! protractor-cucumber-framework@3.1.0 start: `node test/testapp/server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the protractor-cucumber-framework@3.1.0 start script 'node test/testapp/server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the protractor-cucumber-framework package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node test/testapp/server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs protractor-cucumber-framework
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls protractor-cucumber-framework
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\g.ivanova\npm-debug.log

g.ivanova@DESKTOP-1UCJ33I MINGW64 ~
$
Display all 4636 possibilities? (y or n)

g.ivanova@DESKTOP-1UCJ33I MINGW64 ~
$ npm test

> protractor-cucumber-framework@3.1.0 pretest C:\Users\g.ivanova
> npm run lint && multidep test/multidep.js

> protractor-cucumber-framework@3.1.0 lint C:\Users\g.ivanova
> eslint .

EPERM: operation not permitted, scandir 'C:\Users\g.ivanova\AppData\Local\Microsoft\Windows\INetCache\Content.IE5'
Error: EPERM: operation not permitted, scandir 'C:\Users\g.ivanova\AppData\Local\Microsoft\Windows\INetCache\Content.IE5'
    at Error (native)
    at Object.fs.readdirSync (fs.js:952:18)
    at GlobSync._readdir (C:\Users\g.ivanova\node_modules\glob\sync.js:288:41)
    at GlobSync._readdir (C:\Users\g.ivanova\node_modules\eslint\lib\util\glob.js:59:36)
    at GlobSync._readdirInGlobStar (C:\Users\g.ivanova\node_modules\glob\sync.js:267:20)
    at GlobSync._readdir (C:\Users\g.ivanova\node_modules\glob\sync.js:276:17)
    at GlobSync._readdir (C:\Users\g.ivanova\node_modules\eslint\lib\util\glob.js:59:36)
    at GlobSync._processReaddir (C:\Users\g.ivanova\node_modules\glob\sync.js:137:22)
    at GlobSync._process (C:\Users\g.ivanova\node_modules\glob\sync.js:132:10)
    at GlobSync._processGlobStar (C:\Users\g.ivanova\node_modules\glob\sync.js:380:10)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! protractor-cucumber-framework@3.1.0 lint: `eslint .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the protractor-cucumber-framework@3.1.0 lint script 'eslint .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the protractor-cucumber-framework package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs protractor-cucumber-framework
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls protractor-cucumber-framework
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\g.ivanova\npm-debug.log
npm ERR! Test failed.  See above for more details.

In fact the directory is C:\Users\g.ivanova\protractor-cucumber-framework\test\testapp, not sure why C:\Users\g.ivanova\test\testapp was searched instead.

**Comment by darrinholst** [comment]
Not sure on that one. I assume you're in the protractor-cucumber-framework directory since `npm start` was found. The command to start is simply `node test/testapp/server`. Maybe try using a `./`?

    node ./test/testapp/server

**Comment by Syslog2905** [comment]
Yes, I've just fixed a few minutes ago starting form the right directory i.e. C:\Users\g.ivanova\protractor-cucumber-framework. Now the server works:
$ npm start

> protractor-cucumber-framework@3.1.0 start C:\Users\g.ivanova\protractor-cucumber-framework
> node test/testapp/server

Server started on port: 8081
BUT have another issue when did $ npm test:
 163:159  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  164:46   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  165:108  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  166:49   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  167:114  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  168:12   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  169:17   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  170:37   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  171:10   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  172:10   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  173:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  174:51   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  175:39   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  176:83   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  177:10   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  178:10   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  179:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  180:37   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  181:85   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  182:8    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  183:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  184:38   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  185:36   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  186:24   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  187:12   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  188:39   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  189:22   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  190:29   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  191:8    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  192:8    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  193:5    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  194:3    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  195:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  196:27   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  197:92   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  198:15   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  199:2    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  200:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  201:19   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  202:9    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  203:3    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

C:\Users\g.ivanova\protractor-cucumber-framework\test\uncaught-exceptions.spec.js
   1:35   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   2:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   3:45   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   4:64   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   5:101  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   6:25   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   7:84   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   8:46   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   9:14   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  10:6    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  11:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  12:64   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  13:101  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  14:26   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  15:25   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  16:84   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  17:46   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  18:14   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  19:6    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  20:4    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

✖ 17002 problems (17002 errors, 0 warnings)


npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ru   n" "lint"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! protractor-cucumber-framework@3.1.0 lint: `eslint .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the protractor-cucumber-framework@3.1.0 lint script 'eslint .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the protractor-cucumber-framework package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs protractor-cucumber-framework
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls protractor-cucumber-framework
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\g.ivanova\protractor-cucumber-framework\npm-debug.log
npm ERR! Test failed.  See above for more details.
Any clue how to fix this?

**Comment by darrinholst** [comment]
Looks like maybe git or your editor is converting unix style line endings to windows. It's been a while since I've used git on windows, but I believe there is an option to not change line endings on clone.

**Comment by Syslog2905** [comment]
So I should clone the project again with the option to not change line endings?I'll try and let you know then.

**Comment by Syslog2905** [comment]
Still can not workaround this issue. Can not find a way to clone w/t changing line endings. Please advice if I disable lint will this fix the issue? If yes, what lines should I change and where they are in the project? Thanks!

**Comment by darrinholst** [comment]
Sure, disabling linting will not throw those errors anymore. I guess it depends on what you're trying to do. If you're just trying to run the tests locally you can remove the `npm run lint` part from `pretest` in `package.json`. If you're trying to prepare a PR then you're going to have to figure out how to keep the line endings the way they are in the repo.

**Comment by darrinholst** [comment]
[This](http://stackoverflow.com/questions/2517190/how-do-i-force-git-to-use-lf-instead-of-crlf-under-windows) might be of use as well.

**Comment by darrinholst** [comment]
Closing this as I don't believe there's anything to do here. Let me know if you think otherwise.
