### ISSUE TITLE
Cucumber times out when using browser.sleep

### ISSUE THREAD

**Issue by pnakhat** [protractor-cucumber-framework/protractor-cucumber-framework#85]
issue is when I use below code , cucumber timeout. Global timeout is set to be 20 seconds 

`
defineSupportCode(function({setDefaultTimeout}) {
    setDefaultTimeout(20 * 1000);
});`

`browser.sleep(10000).then(
            function(){
                console.log("Waiting");
            }
        )`

Error log

` Error: function timed out after 20000 milliseconds
     at Timeout.<anonymous> (C:\code\cucumber-js\node_modules\cucumber\lib\user_code_runner.js:91:22)
     at ontimeout (timers.js:386:14)
     at tryOnTimeout (timers.js:250:5)
     at Timer.listOnTimeout (timers.js:214:5)
`
**Version of  plugins**

`   "chai": "^3.5.0",
    "chai-as-promised": "^6.0.0",
    "cucumber": "^2.1.0",
    "cucumber-html-report": "^0.6.0",
    "cucumber-html-reporter": "^0.4.2",
    "install": "^0.10.1",
    "npm": "^4.6.1",
    "protractor": "^5.1.0",
    "protractor-cucumber-framework": "^3.1.0",
    "protractor-screenshot-reporter": "0.0.5"`

**Comment by darrinholst** [comment]
Please see this [example repo](https://github.com/dholst/protractor-cucumber-framework-timeouts) of timeouts working as expected. 

<img width="330" alt="1__tmux_-2_attach____tmux_-2_new__tmux_" src="https://cloud.githubusercontent.com/assets/4854/26355430/3f06933e-3f8e-11e7-9d29-19b9a33fee23.png">
