### ISSUE TITLE
Custom formatters with outputfile not working anymore

### ISSUE THREAD

**Issue by otijhuis** [protractor-cucumber-framework/protractor-cucumber-framework#87]
The regular expression in the function `makeFormatPathsUnique` causes custom formatters to fail.
Normally you could specify `"./some_dir/custom_formatter.js:some_dir/outputfile"`. Now it only finds 'words' before the colon. This means only `js` gets passed to cucumber, not `./some_dir/custom_formatter.js` like it should.

```javascript
function makeFormatPathsUnique(values) {
    return toArray(values).map(function(format) {
      let formatPathMatch = format.match(/(\w+:)(.+)/);

      if (!formatPathMatch) return format;

      let pathParts = formatPathMatch[2].split('.');
      pathParts.splice(pathParts.length - 1, 0, process.pid);
      return formatPathMatch[1] + pathParts.join('.');
    });
  }
```

**Comment by darrinholst** [comment]
Thanks for the report. v3.1.2 should fix this.
