### ISSUE TITLE
Using rerun of failed tests with @rerun.txt 

### ISSUE THREAD

**Issue by Boxdove** [protractor-cucumber-framework/protractor-cucumber-framework#89]
Hi, could you please help me how to use in appropriate way this feature. 
I use cucumber 1.3.3, protractor-cuumber-framework 2.0.0

At present I have format: ['pretty', 'rerun:@rerun.txt'] in config.js, it creates @rerun.text file with failed scenarios
but have no idea how to run this file again 
If I create separate Rerun formatter feature, @rerun.txt file might be run after all features... 
What did I miss? 

Thank you

**Comment by darrinholst** [comment]
You need to pass in the rerun argument with the file as the value. An example is [here](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/blob/master/test/rerun.spec.js#L5)

**Comment by darrinholst** [comment]
you'll also need to be using at least version [2.2.0](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/releases/tag/2.2.0)

**Comment by darrinholst** [comment]
let us know if it doesn't work

**Comment by Boxdove** [comment]
Sorry for late replay.
Thanks a lot, that's all I needed)

**Comment by kieranbop** [comment]
The example doesn't show how we use protractor cucumber to create that @rerun file @darrinholst . When I append the various options after it will just hang and not write the failing scenarios to the file.

**Comment by darrinholst** [comment]
you have to run it the first time with a rerun formatter - `--format rerun:@rerun.txt`
