### ISSUE TITLE
Undefined steps found

### ISSUE THREAD

**Issue by vinodkpasi** [protractor-cucumber-framework/protractor-cucumber-framework#90]
I have written script Using protractor/protractor-cucumber-framework.js/cucumber.js
I used below commands:
npm install protractor
npm install cucumber
npm install protractor-cucumber-framework

While running the script I am getting the error message.
![image](https://user-images.githubusercontent.com/25478920/28726917-b97d606c-73e0-11e7-9cf7-54fb764ee66e.png)
Note: If use below commands to install cucumber/protractor-cucumber-framework everything is working file.
npm install cucumber@0.10.2
npm install protractor-cucumber-framework@0.5.0

These are project files:
**test.feature**
Feature: Sample Test
Scenario: Protractor and Cucumber Test
Given I go to the application

**mystep.js**
var myStepDefinitionsWrapper = function () {
this.Given('I go to the application', function (callback) {
callback();
});
}
module.exports = myStepDefinitionsWrapper;

**Config.js**
//protractor.conf.js
//require.resolve('protractor-cucumber-framework')
exports.config = {
framework: 'custom',
frameworkPath: require.resolve('protractor-cucumber-framework'),
directConnect:true,
capabilities: {
'browserName': 'chrome'
},

// Spec patterns are relative to this directory.
specs: [
    'test.feature'
],

baseURL: 'http://localhost:8080/',

cucumberOpts: {
   require: 'mysteps.js'
}
};

**Comment by darrinholst** [comment]
Step definitions are not compatible between cucumber 2+ and pre cucumber 2. Please see an example [here](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/blob/master/test/cucumber/stepDefinitions/cucumber2Steps.js) of how to define steps for cucumber 2.

**Comment by vinodkpasi** [comment]
Thanks...
