### ISSUE TITLE
Access to Hooks

### ISSUE THREAD

**Issue by SGoldenGraham** [protractor-cucumber-framework/protractor-cucumber-framework#91]
No ability to access Before/After Features/Step Hooks

**Comment by darrinholst** [comment]
Can you elaborate on what issue you are seeing? An example of how you would define them is [here](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/hooks.md)

**Comment by SGoldenGraham** [comment]
Sorry for the minimal description. I am attempting to automate logging in and out at the start and end of a feature. So I need to hook into when a feature before and after events. I understand tags can be used but tags applied to the feature level are just applied to every scenario. So every scenario ends up logging in and out. So in short I want to apply a tag to target a feature and not every scenario in a feature.

**Comment by AlexandrosD** [comment]
This is the way hooks work. You could achieve what you intend to do by
utilizing cucumber's event listeners, e.g BeforeFeature.

**Comment by SGoldenGraham** [comment]
I am using the defineSupportCode syntax as outlined here: https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/api_reference.md. However it doesn't support the BeforeFeature. I only have access to Before and BeforeAll. Am I unable to use this style as outlined in the cucumber2 examples if I want to use the event listeners? I was hoping I would have access to the registerHandle function.

There seems like there used to be a webpage about event handlers but its returning 404 at the moment:
https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/event_handlers.md

**Comment by darrinholst** [comment]
Looks like `registerHandler` is going to be removed in the next major release, but you should still be able to use it for 2.x. 

[2.3.1 registerHandler](https://github.com/cucumber/cucumber-js/blob/v2.3.1/docs/support_files/api_reference.md#registerhandlerevent-options-fn)

[2.3.1 Event Handlers](https://github.com/cucumber/cucumber-js/blob/v2.3.1/docs/support_files/event_handlers.md)

**Comment by SGoldenGraham** [comment]
That worked! Thanks very much, this is a great library guys! Any idea what will replace registerHandler? It seems like a lot of people use it?

**Comment by darrinholst** [comment]
from the changelog...

> Remove registerHandler and registerListener. Use BeforeAll / AfterAll for setup code. Use the event protocol formatter if used for reporting. Please open an issue if you have another use case.
