### ISSUE TITLE
cucumber 3.x support

### ISSUE THREAD

**Issue by darrinholst** [protractor-cucumber-framework/protractor-cucumber-framework#92]
`registerHandler` is being removed in the next major release. We use it pretty extensively to capture the results [here](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/blob/master/lib/resultsCapturer.js#L12). We'll have to adapt that to work with 3.x.

**Comment by dherges** [comment]
The changelog says to use the event procol formatter:

- https://github.com/cucumber/cucumber-js/blob/master/src/formatter/event_protocol_formatter.js
- https://docs.cucumber.io/event-protocol/

**Comment by edgarechm** [comment]
And what is the workaround? My scripts are failing because of this.

Unhandled rejection TypeError: this.registerHandler is not a function
    at Object.registerHandlers (/var/lib/jenkins/workspace/project1/node_modules/protractor-cucumber-framework/lib/resultsCapturer.js:16:8)

**Comment by FarhadG** [comment]
I'm getting the same thing...

**Comment by darrinholst** [comment]
There is no workaround. This framework doesn't support cucumber 3 yet. Stick with cucumber 2 until somebody makes that happen.

**Comment by dherges** [comment]
If someone figures out how this EventProtocolFormatter is to be used, that will help!

It need to be implemented in the code @darrinholst mentioned.

**Comment by edgarechm** [comment]
@FarhadG ... what worked for me is forcing the version of the packages in my build. The version of cucumber in the package is the problem. So after installing the protractor-cucumber-framework, be sure to install the latest version of cucumber that worked for you. For me was version 2.3.1. So in my package.jaons I have this this:

```
"cucumber": "2.3.1",
"protractor-cucumber": "0.1.8",
"protractor-cucumber-framework": "3.1.0"
```

... or manually installing the packages would be like this:

```
npm install protractor-cucumber@0.1.8 --save-dev --save-exact;
npm install protractor-cucumber-framework@3.1.0 --save-dev --save-exact;
npm install cucumber@2.3.1 --save-dev --save-exact;
```

**Comment by FarhadG** [comment]
Thanks for the comment, @edgarechm . I went through the very same process and ended up matching the dependencies within this repo. So far, so great! It may be useful to you to up some of your versions:

```
    "cucumber": "^2.3.1",
    "protractor": "^5.1.2",
    "protractor-cucumber-framework": "^3.1.2"
```

**Comment by navalkgupta** [comment]
One can refer below test repository for latest dependencies working nicely together with latest versions of protractor, cucumber, protractor-cucumber-framework and cucumber-html-repot
https://github.com/navalkgupta/protractor-cucumber-tests

**Comment by wswebcreation** [comment]
@navalkgupta 

Your repo works with CucumberJS 2 instead of 3

**Comment by wswebcreation** [comment]
@darrinholst 

Tnx for fixing this that quick, kuddo's for you!! 💪🏻💪🏻

**Comment by FarhadG** [comment]
Thanks for the update, @darrinholst. This is awesome!

One thing I've noticed now is that I get the following error with the migration to cucumber 3:

`Unhandled rejection Error: Cannot find module '/Users/......../......../pretty'`

It seems that the cucumber options no longer accept `pretty`?

**Comment by darrinholst** [comment]
@FarhadG that appears to be correct according to the [changelog](https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md#300-2017-08-08)
