### ISSUE TITLE
protractor cucumber throwing error as describe in below

### ISSUE THREAD

**Issue by vikram006** [protractor-cucumber-framework/protractor-cucumber-framework#94]
Hello friends i testing my angular 2 app using protractor and cucumber js but it give me this error i try several solution for this issue but no one can solve my issue.if you know any sol it would be great thank u..

> `[1] Unhandled rejection TypeError: this.registerHandler is not a function [1] at Object.registerHandlers (/home/ca1/WebstormProjects/DME/node_modules/protractor-cucumber-framework/lib/resultsCapturer.js:16:8) [1] at /home/ca1/WebstormProjects/DME/node_modules/protractor-cucumber-framework/lib/resultsCapturer.js:6:22 [1] at Object.defineSupportCode (/home/ca1/WebstormProjects/DME/node_modules/cucumber/src/support_code_library_builder/index.js:20:9) [1] at Object. (/home/ca1/WebstormProjects/DME/node_modules/protractor-cucumber-framework/lib/resultsCapturer.js:5:12) [1] at Module._compile (module.js:570:32) [1] at Object.Module._extensions..js (module.js:579:10) [1] at Module.load (module.js:487:32) [1] at tryModuleLoad (module.js:446:12) [1] at Function.Module._load (module.js:438:3) [1] at Module.require (module.js:497:17) [1] at require (internal/module.js:20:19) [1] at /home/ca1/WebstormProjects/DME/node_modules/cucumber/src/cli/index.js:61:42 [1] at Array.forEach (native) [1] at Cli.getSupportCodeLibrary (/home/ca1/WebstormProjects/DME/node_modules/cucumber/src/cli/index.js:61:22) [1] at Cli. (/home/ca1/WebstormProjects/DME/node_modules/cucumber/src/cli/index.js:76:37) [1] at next (native) [1] [17:30:50] E/launcher - BUG: launcher exited with 1 tasks remaining

`

**Comment by wswebcreation** [comment]
Are you using CucumberJS 3? If so then downgrade it to 2 because 3 isn't supported yet

**Comment by vikram006** [comment]
here is my configuration
`"devDependencies": {
	  "protractor": "5.1.2",
	  "cucumber": "2.3.1",
	  "protractor-cucumber-framework": "3.1.2",
	  "chai": "3.5.0",
	  "chai-as-promised": "6.0.0",
	  "cucumber-html-reporter": "2.0.0",
	  "grunt-protractor-runner": "5.0.0"
  },`

**Comment by wswebcreation** [comment]
Can you paste your config and your script here, or give an example repo so we can check it?

**Comment by vikram006** [comment]
downgrading solve my issue sorry I forget to mention it..thank u

**Comment by wswebcreation** [comment]
Can you close this issue then?

**Comment by vikram006** [comment]
yes
