### ISSUE TITLE
Unhandled rejection Error: no such file or directory, resultsCapturer.js:.will-be-removed-after-cucumber-runs.tmp'

### ISSUE THREAD

**Issue by VaaniSai** [protractor-cucumber-framework/protractor-cucumber-framework#95]
I am trying to automate an Angular 4 application. When I run "protractor config.js"

When I have format option in my config.ts file to something like this:
**format: ['json:../reporting/results.json']**

I get the error saying:
**Unhandled rejection Error: ENOENT: no such file or directory, open 'C:\MyWorkspace\ProtractorProjects\protractor-cucumber-sample\test\config\MyWorkspace\ProtractorProjects\protractor-cucumber-sample\node_modules\protractor-cucumber-framework\lib\resultsCapturer.js:.will-be-removed-after-cucumber-runs.tmp'
    at Error (native)

Process finished with exit code 100
Empty test suite.**

I could understand that it is unable to reach "resultsCapturer.js". Am not sure where I should change.

When I change format option to:
format: ['pretty']

_I get an error:_
**Unhandled rejection Error: Cannot find module 'C:\MyWorkspace\protractor-cucumber-sample\test\config\pretty'
    at Function.Module._resolveFilename (module.js:469:15)**

I also checked [this docs](https://www.typescriptlang.org/docs/handbook/modules.html#ambient-modules) but could not help me to fix the issue

_Below are my project details:_

node version: v6.10.3
protractor version: 5.1.2

**config.ts:**

    import { Config } from 'protractor';
     
    export let config: Config = {
     
        seleniumAddress: 'http://localhost:4444/wd/hub',
        specs: ["../features/*.feature"],
     
        framework: 'custom',
        frameworkPath: require.resolve('protractor-cucumber-framework'),
     
        baseUrl: "http://localhost:4200/",
     
        cucumberOpts: {
            compiler: "ts:ts-node/register",
            strict: true,
            format: ['json:../reporting/results.json'],
            require: ['../steps/*.js'],
            tags: '@smoke'
        }
    }

**tsconfig.json:**

    {
      "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "moduleResolution": "node",
        "sourceMap": true,
        "typeRoots": [
          "./node_modules/@types/"
        ],
        "lib": [
        "es2015"
        ],
        
        "strict": true
      }
    }

**package.json:**

    {
      "name": "protractor-cucumber-sample",
      "version": "0.0.0",
      "private": true,
      "scripts": {
        "start": "node ./bin/www"
      },
      "dependencies": {
        "@types/jasmine": "^2.5.53",
        "body-parser": "~1.17.1",
        "cookie-parser": "~1.4.3",
        "debug": "~2.6.3",
        "express": "~4.15.2",
        "jade": "~1.11.0",
        "morgan": "~1.8.1",
        "serve-favicon": "~2.4.2"
      },
      "devDependencies": {
        "@types/chai": "^4.0.3",
        "@types/cucumber": "^2.0.3",
        "@types/mkdirp": "^0.5.0",
        "chai": "^4.1.1",
        "chai-as-promised": "^7.1.1",
        "cucumber": "^3.0.0",
        "cucumber-html-reporter": "^2.0.3",
        "jasmine": "^2.7.0",
        "jasminewd2": "^2.1.0",
        "protractor-cucumber-framework": "^4.0.2",
        "ts-node": "^3.3.0",
        "typescript": "^2.4.2"
      }
    }﻿

Please let me know If I need to produce additional info which helps you to address this issue.
	
Also please suggest if this is not the right forum for this question or in case you know other forums where this question can be posted.

Thanks in advance.

**Comment by darrinholst** [comment]
What's happening is that cucumber is splitting the format argument on `:` which, on Windows, results in `['C', '\absolute\path\to\resultsCapturer.js', 'tempfile']`. Not sure how to handle this yet. Maybe using a UNC path like `/localhost/C$` or figure out the relative path to `resultsCapturer.js` somehow?

**Comment by darrinholst** [comment]
@VaaniSai see if v4.0.3 resolves your issue. Reopen if not.

**Comment by VaaniSai** [comment]
Thanks for your reply. If we notice the absolute path in the error..

`C:\MyWorkspace\ProtractorProjects\protractor-cucumber-sample\test\config\MyWorkspace\ProtractorProjects\protractor-cucumber-sample\node_modules\protractor-cucumber-framework\lib\resultsCapturer.js:.will-be-removed-after-cucumber-runs.tmp`

the absolute path of **"config.js"** file is getting added i.e. `C:\MyWorkspace\ProtractorProjects\protractor-cucumber-sample\test\config`

then it adds absolute path of  **resultsCapturer.js**. i.e. `\MyWorkspace\ProtractorProjects\protractor-cucumber-sample\node_modules\protractor-cucumber-framework\lib\resultsCapturer.js`

I'll try the new version and will update you.

**Comment by Neal910** [comment]
I am using similar setting:

```
cucumberOpts: {   
        compiler: "ts:ts-node/register",    
        strict: true,
        format: ['pretty'],
        require: ['../steps/*.js'],
        tags: '@smoke'
    }
````
with  `"protractor-cucumber-framework": "^4.0.9",`

Still get following error: 
"Unhandled rejection Error: Cannot find module '/\<absoluate path\>/protractor/pretty' "

**Comment by darrinholst** [comment]
`pretty` [was removed](https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md#300-2017-08-08) in 3.0.0

**Comment by shekhara-OUP** [comment]
I am trying to run my conf.js file i am getting Unhandled rejection Error: Cannot find module 'D:\mAVEN_wORKSPACE2\NewCucumberProtractorProject\pretty'


My Conf file is:
exports.config = {
		 //directConnect: true,
		seleniumAddress: 'http://127.0.0.1:4444/wd/hub',
		ignoreUncaughtExceptions: true,
  getPageTimeout: 60000,
  allScriptsTimeout: 500000,
  framework: 'custom',
  // path relative to the current config file
  frameworkPath: require.resolve('protractor-cucumber-framework'),
  capabilities: {
    'browserName': 'chrome'
  },

  // Spec patterns are relative to this directory.
  specs: [
    'Feature/*.feature'
  ],

  baseURL: 'https://stackoverflow.com/questions/33763934/error-cannot-find-module-pretty-bytes',

  cucumberOpts: {
    require: 'stepdefinition/stepDefinitions.js',
    tags: false,
    format:  'pretty:target/cucumber-pretty.txt',
    profile: false,
    'no-source': true
  }
  };


i already have pretty in my node_modules folder
Can u pls help me to resolve my error

**Comment by darrinholst** [comment]
if it's in your node_modules folder then the config would be `format: 'node_modules/pretty:target/cucumber-pretty.txt',`
