### ISSUE TITLE
After assertion failure next steps are not executed

### ISSUE THREAD

**Issue by vinodkpasi** [protractor-cucumber-framework/protractor-cucumber-framework#98]
After first assertion failure next steps are not executed and execution terminates with error message "Process exited with error code 199".

**test.feature**
Feature: Sample Test
Scenario: Protractor and Cucumber Test
Given I go to the application

**mysteps.js**
var chai = require('chai');
var chaiAsPromised = require('chai-as-promised');

chai.use(chaiAsPromised);
var expect = chai.expect;

var myStepDefinitionsWrapper = function () {
    this.Given('I go to the application', { timeout: 60 * 1000 }, function (callback) {
        browser.ignoreSynchronization = true;
        browser.get('https://help.github.com/categories/github-pages-basics/');
        expect(browser.getTitle()).to.eventually.equal('GitHub Helps');
        element(by.id('quicksearch-query')).sendKeys('Hi...')
        browser.sleep(5000).then(function () {
            callback();
        })
    });
}
module.exports = myStepDefinitionsWrapper;

**Config.js**
exports.config = {
    framework: 'custom',
    frameworkPath: require.resolve('protractor-cucumber-framework'),
    directConnect: true,
    chromeDriver: 'C:/Drivers/chromedriver.exe',
    specs: [
        'test.feature'
    ],
    cucumberOpts: {
        require: 'mysteps.js',
    },
};

**Error Message**
C:\Users\PASI\Documents\Visual Studio 2013\WebSites\ProtractorApp>protractor Config.js
[07:12:06] I/launcher - Running 1 instances of WebDriver
[07:12:06] I/direct - Using ChromeDriver directly...
Feature: Sample Test

  Scenario: Protractor and Cucumber Test
[07:12:11] E/launcher - expected 'GitHub Help' to equal 'GitHub Helps'
[07:12:11] E/launcher - AssertionError: expected 'GitHub Help' to equal 'GitHub Helps'
    at getBasePromise.then.then.newArgs (C:\Users\PASI\Documents\Visual Studio 2013\WebSites\ProtractorApp\node_modules\chai-as-promised\lib\chai-as-promised.js:302:22)
    at ManagedPromise.invokeCallback_ (C:\Users\PASI\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1366:14)
    at TaskQueue.execute_ (C:\Users\PASI\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2970:14)
    at TaskQueue.executeNext_ (C:\Users\PASI\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2953:27)
    at asyncRun (C:\Users\PASI\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2813:27)
    at C:\Users\PASI\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:109:7)
[07:12:11] E/launcher - Process exited with error code 199

**Comment by wswebcreation** [comment]
Can you tell more about your setup, so which versions you are using of:

- Protractor
- Cucumber
- protractor-cucumber-framework

And can you also format your code examples like this by using syntax highlighting, see also [here](https://guides.github.com/features/mastering-markdown/)

```js
var chai = require('chai');
var chaiAsPromised = require('chai-as-promised');

chai.use(chaiAsPromised);
var expect = chai.expect;

var myStepDefinitionsWrapper = function() {
  this.Given('I go to the application', {
    timeout: 60 * 1000
  }, function(callback) {
    browser.ignoreSynchronization = true;
    browser.get('https://help.github.com/categories/github-pages-basics/');
    expect(browser.getTitle()).to.eventually.equal('GitHub Helps');
    element(by.id('quicksearch-query')).sendKeys('Hi...')
    browser.sleep(5000).then(function() {
      callback();
    })
  });
}
module.exports = myStepDefinitionsWrapper;
```

**Comment by darrinholst** [comment]
Try `ignoreUncaughtExceptions: true` as explained [here](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework#uncaught-exceptions)

**Comment by vinodkpasi** [comment]
Below ia the version details
protractor version: 5.1.2
protractor-cucumber-framework version: 3,10.10

**Comment by wswebcreation** [comment]
@vinodkpasi 

And your version of Cucumber?
And besides from your code you posted here, you don't have any code in the project, like hooks and so on?

**Comment by darrinholst** [comment]
When you write 
``` js
expect(browser.getTitle()).to.eventually.equal('GitHub Helps');
```
 that is running asynchronously. If (and when in your case) it fails it will throw an exception which is uncaught since it is running asynchronously. Protractor catches that [here](https://github.com/angular/protractor/blob/c525ca6b277a6a8fea43632ae493c13999cddc94/lib/launcher.ts#L186). If you don't explicitly ignore this situation with `ignoreUncaughtExceptions: true` in your protractor config it will exit the process.

I'm not sure what the purpose is of the sleep, but another way to write that step would be

``` js
this.Given('I go to the application', function() {
  browser.ignoreSynchronization = true;
  browser.get('https://help.github.com/categories/github-pages-basics/');

  return browser.getTitle()
    .then(title => expect(title).to.eql('GitHub Helps'))
    .then(() => element(by.id('quicksearch-query')).sendKeys('Hi...'));
});
```

which would return a promise where the exception handling logic would be handled by cucumber instead of bubbling back up to protractor.

...or `ignoreUncaughtExceptions: true`

**Comment by wswebcreation** [comment]
@darrinholst 

Tnx for helping out. Didn't thought about that

**Comment by darrinholst** [comment]
reopen if one of these suggestions doesn't solve your problem
